### ISSUE TITLE
Bot crashing constantly with log file in use error

### ISSUE THREAD

**Issue by peterbaumert** [Necrobot-Private/NecroBot#1127]
[22:12:07] (FEHLER) Error: System.IO.IOException: The process cannot access the file '*\NecroBot2.WIN\Logs\NecroBot2-2017-03-01-22-11-49.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at PoGo.NecroBot.Logic.Logging.FileLogger.Write(String message, LogLevel level, ConsoleColor color) in c:\projects\necrobot2\PoGo.NecroBot.Logic\Logging\FileLogger.cs:line 78
   at PoGo.NecroBot.Logic.Logging.Logger.Write(String message, LogLevel level, ConsoleColor color, Boolean force) in c:\projects\necrobot2\PoGo.NecroBot.Logic\Logging\Logger.cs:line 72
   at PoGo.NecroBot.Logic.Inventory.GetDuplicatePokemonToTransfer(IEnumerable`1 pokemonsNotToTransfer, Dictionary`2 pokemonEvolveFilters, Boolean keepPokemonsThatCanEvolve, Boolean prioritizeIVoverCp) in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 260
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.HumanRandomActionTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanRandomActionTask.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 101

**Comment by samuraitruong** [comment]
delete this file -?'*\NecroBot2.WIN\Logs\NecroBot2-2017-03-01-22-11-49.txt'

**Comment by samuraitruong** [comment]
and make sure you able to make new file in logs folder

**Comment by peterbaumert** [comment]
did all that, still happening :( also made exclusion for antivirus etc. there isn't any "other" program trying to access the file

**Comment by samuraitruong** [comment]
did you run bot on share network folder?

**Comment by peterbaumert** [comment]
its on my desktop which is on D:

**Comment by peterbaumert** [comment]
![capture](https://cloud.githubusercontent.com/assets/1212934/23483066/a9e67ea6-fed1-11e6-8898-cd9489096fc1.PNG)
screenshot of the log

**Comment by samuraitruong** [comment]
copy bot to other folder. don't put on desktop and clear everything in logs, re-run it

**Comment by peterbaumert** [comment]
seems to have fixed it, thanks!
