### ISSUE TITLE
Error while traveling to a chosen location

### ISSUE THREAD

**Issue by TaylorZaneKirk** [Necrobot-Private/NecroBot#1141]
Attaching log as the bot told me to do.

```
[12:23:55] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[12:23:55] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":2046521325,"Requests":[{"RequestType":101,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,52,48,52,55,52,50,53,53,56,54,49,50,53,51,17,23,184,31,98,131,97,68,64,25,123,69,22,219,164,126,82,192,33,201,175,31,98,131,97,68,64,41,172,59,22,219,164,126,82,192]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,165,251,141,130,169,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,99,49,102,50,54,49,49,98,102,57,49,100,48,49,57,102,48,97,54,54,48,101,54,102,51,56,98,48,99,51,97,50,54,97,51,54,98,97,53,48]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,141,196,23,22,123,238,34,188,68,105,62,13,65,220,50,153,36,71,146,241,56,85,145,126,230,20,13,165,157,97,158,56,79,84,246,173,180,158,119,211,50,243,94,237,243,236,88,126,15,112,121,217,0,21,107,213,217,79,131,182,139,31,4,182,197,121,35,205,225,205,24,253,118,112,51,26,238,132,28,234,152,0,18,129,114,254,168,98,24,4,175,192,120,69,95,11,53,206,18,87,198,208,53,121,138,28,31,124,32,97,237,57,61,23,54,90,130,209,125,183,212,3,73,190,176,111,56,170,114,161,102,0,64,106,42,192,230,151,79,157,58,224,76,3,44,199,126,44,176,129,107,123,196,2,9,233,77,84,143,0,102,224,252,222,244,82,31,164,87,208,198,227,186,182,208,27,56,4,134,100,229,208,12,81,76,230,225,150,184,241,237,130,44,170,168,101,112,62,78,85,84,156,97,4,161,241,65,176,224,237,247,204,240,217,128,48,145,131,122,200,59,204,19,148,130,194,239,26,185,229,151,149,208,43,22,205,1,16,236,80,61,194,170,84,145,122,217,101,45,53,163,183,144,31,98,0,27,246,189,222,128,187,152,189,82,185,172,187,38,229,56,233,151,122,103,154,144,175,116,91,108,3,222,145,25,43,7,203,68,149,50,161,38,239,173,124,131,222,23,113,253,179,81,90,52,151,46,1,138,234,76,151,228,150,27,60,133,28,56,140,26,51,210,148,237,55,192,5,134,205,79,40,145,55,252,37,94,97,89,25,95,178,115,225,125,10,28,245,154,108,189,135,93,167,173,218,58,175,19,88,87,132,107,167,162,10,115,30,156,63,56,91,63,69,109,178,6,248,78,213,106,72,237,234,227,214,64,19,136,176,117,65,138,77,102,74,26,18,242,77,10,239,11,239,80,193,213,24,250,46,77,205,28,129,25,121,113,231,156,223,124,40,7,66,93,204,204,191,199,18,150,137,235,147,95,102,149,254,125,235,41,195,146,194,169,147,212,234,59,86,9,100,126,229,76,185,66,199,236,146,196,66,113,8,189,62,114,81,188,219,123,144,77,178,54,101,232,0,11,166,184,23,13,80,94,127,204,231,0,38,37,15,17,52,91,239,14,173,103,98,235,55,62,100,216,175,129,184,255,204,177,112,63,84,212,26,147]}],"Latitude":40.761822000015108,"Longitude":-73.978812000035688,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[197,42,239,194,149,35,2,197,57,113,138,154,48,38,124,54,159,222,181,224,246,56,206,227,168,196,121,165,85,146,238,36,103,87,29,67,52,65,177,23,152,5,212,30,211,105,48,198,20,217,29,64,130,234,137,162,27,138,255,216,60,219,253,198,249,188,233,24,196,50,15,143,139,208,74,231,138,221,14,192],"ExpireTimestampMs":1488480449405,"End":[217,213,233,75,249,55,5,246,121,95,251,105,252,189,13,5]},"MsSinceLastLocationfix":11770}
[12:23:55] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<SearchFort>d__2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<FarmPokestop>d__17.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 391
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<DoActionAtPokeStop>d__15.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 101
```

**Comment by samuraitruong** [comment]
is it happen consistently,  I mean did you reproduce it every time select move to location

**Comment by TaylorZaneKirk** [comment]
@samuraitruong No, I believe it is actually tied to when the bot is running and a new update goes live. If I continue without updating it will log-in, act normally for about 10 minutes, then same error occurs. As soon as I allow for update, all goes well.

**Comment by samuraitruong** [comment]
so do we happy to close this issue?
