### ISSUE TITLE
Bad Request Exception

### ISSUE THREAD

**Issue by duke2906** [Necrobot-Private/NecroBot#1156]
As the attached Exception says that this error is supposed to be reported to dev... so her it is...

### (OPTIONAL) Your Log:
```
[22:06:37] (FEHLER) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[22:06:37] (FEHLER) BAD REQUEST 
{"StatusCode":2,"RequestId":823564444,"Requests":[{"RequestType":101,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,52,49,55,49,54,51,56,50,49,49,54,53,56,48,17,105,18,236,0,161,110,73,64,25,146,54,62,209,144,100,35,64,33,169,102,30,113,161,110,73,64,41,0,0,0,144,142,100,35,64]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,193,192,243,175,169,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,99,49,102,50,54,49,49,98,102,57,49,100,48,49,57,102,48,97,54,54,48,101,54,102,51,56,98,48,99,51,97,50,54,97,51,54,98,97,53,48]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,149,254,186,30,92,255,59,241,134,192,235,52,145,78,245,127,167,210,5,74,155,82,49,79,42,238,14,150,67,136,85,0,176,119,159,125,203,72,182,29,31,97,103,244,175,180,242,128,78,31,26,75,138,198,174,250,131,216,235,167,106,129,191,159,228,228,80,72,50,234,210,121,122,95,29,219,23,251,216,166,105,25,200,247,226,251,75,54,158,238,247,160,43,195,207,161,223,155,84,91,185,195,34,170,190,65,159,90,54,213,112,111,7,103,61,101,58,141,175,167,166,169,18,24,187,212,143,143,197,70,138,140,115,186,18,253,149,149,187,216,150,235,100,239,95,80,205,77,9,187,22,128,60,93,82,226,219,117,18,209,1,4,174,187,158,151,205,129,133,53,212,92,103,80,96,112,11,113,108,192,66,93,96,184,66,32,15,99,163,92,58,96,155,32,71,47,169,14,42,74,179,34,96,121,238,163,138,175,170,104,221,219,219,73,145,32,18,51,116,38,126,151,244,229,2,150,118,101,72,23,244,123,249,157,64,47,173,143,113,69,240,117,18,182,186,39,117,79,15,63,172,239,238,158,177,93,255,172,147,92,252,123,203,62,83,50,54,139,200,19,73,213,254,13,177,76,191,253,91,39,102,96,147,75,173,107,2,207,131,245,11,69,194,185,146,252,21,232,17,164,156,163,69,141,29,217,174,242,236,156,123,52,91,58,239,10,44,8,192,34,130,93,155,231,2,205,174,68,82,82,16,231,222,49,89,126,94,47,112,191,39,228,194,99,208,167,36,84,192,214,217,66,29,28,36,163,98,126,156,20,196,34,122,114,186,237,97,99,108,206,129,208,246,91,156,108,196,187,28,63,242,109,251,4,155,84,248,199,242,1,66,148,198,223,150,234,191,249,177,175,80,190,88,147,12,197,173,212,187,100,192,189,82,163,69,29,150,115,230,68,10,245,32,142,207,122,79,41,192,252,237,101,126,29,184,70,16,188,126,88,215,69,213,247,71,116,244,66,126,191,232,231,233,65,96,117,148,232,243,2,237,17,75,56,110,193,136,140,186,175,61,174,84,224,14,220,40,240,57,41,187,133,209,90,41,157,44,8,119,93,57,112,250,237,255,116,45,115,136,8,196,254,12,122,70,207,142,242,41,146,155,142,206,122,97,121,18]}],"Latitude":50.864288440007677,"Longitude":9.6964173687404447,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[88,146,194,7,101,172,126,231,14,156,39,125,73,124,93,36,143,155,163,146,255,235,232,180,110,88,9,42,0,20,39,76,85,153,77,236,112,88,5,208,91,112,199,133,222,139,105,149,3,222,39,88,33,116,211,171,127,2,90,199,155,48,114,72],"ExpireTimestampMs":1488575827412,"End":[240,184,90,2,19,65,206,188,245,50,2,45,63,73,151,42]},"MsSinceLastLocationfix":21125}
[22:06:37] (FEHLER)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<SearchFort>d__2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<FarmPokestop>d__17.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<DoActionAtPokeStop>d__15.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 307
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 101
```

### Detailed Steps to Reproduce:
Just having Bot active

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:

**Comment by hardknoxni69a** [comment]
attaching #956

**Comment by hardknoxni69a** [comment]
attaching to #1162
