### ISSUE TITLE
After transfer, got Bad Request message.

### ISSUE THREAD

**Issue by isveryfunny** [Necrobot-Private/NecroBot#1162]
After transfer, got Bad Request message.

[22:15:53] (TRANSFERRED) Machop	- CP: 814  IV: 64.44%   [Best CP: 124  IV: 95.56%] (Candies: 125)
[22:15:53] (TRANSFERRED) Machop	- CP: 875  IV: 62.22%   [Best CP: 124  IV: 95.56%] (Candies: 125)
[22:15:53] (TRANSFERRED) Pidgeotto	- CP: 890  IV: 93.33%   [Best CP: 890  IV: 93.33%] (Candies: 44)
[22:15:53] (TRANSFERRED) Crobat	- CP: 1216  IV: 44.44%   [Best CP: 630  IV: 100.00%] (Candies: 193)
[22:15:54] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[22:15:54] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":495149562,"Requests":[{"RequestType":112,"RequestMessage":[]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,172,243,175,205,169,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,99,49,102,50,54,49,49,98,102,57,49,100,48,49,57,102,48,97,54,54,48,101,54,102,51,56,98,48,99,51,97,50,54,97,51,54,98,97,53,48]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,153,155,210,113,48,131,113,83,166,24,7,237,132,200,114,143,11,34,193,127,124,27,80,157,245,110,11,149,118,24,56,188,31,143,227,239,208,51,185,224,68,9,255,206,50,215,12,232,108,33,147,163,32,160,230,30,249,201,17,165,46,180,255,175,187,181,213,49,222,195,7,245,150,120,200,237,156,116,166,57,42,83,110,58,96,154,38,255,212,205,225,30,204,164,111,173,62,166,39,3,169,99,229,184,151,23,214,45,229,255,24,76,85,33,147,107,185,65,197,99,177,141,69,51,18,115,49,223,47,235,169,3,154,108,62,212,149,204,69,240,28,24,67,134,57,6,217,192,140,9,40,185,13,243,100,106,52,235,17,104,88,215,35,6,120,20,237,20,55,61,169,135,205,166,30,193,147,251,93,21,172,130,174,4,29,144,234,19,144,95,136,74,92,191,123,19,238,254,240,216,246,217,230,103,111,131,235,114,47,76,10,139,207,71,240,91,173,101,143,20,58,3,90,201,71,8,195,172,167,28,249,225,243,60,167,222,59,128,56,186,160,242,50,162,108,163,194,177,37,66,188,76,39,188,146,37,125,90,154,151,7,90,205,161,43,253,161,30,70,185,220,7,210,66,238,26,105,210,95,126,163,213,129,68,22,216,106,223,79,86,124,194,69,87,102,201,118,252,139,239,32,123,198,181,197,90,231,71,56,141,21,11,110,207,166,147,115,62,145,103,202,243,250,195,118,68,19,183,255,193,85,229,179,74,162,151,146,113,40,16,15,226,133,147,120,68,216,119,142,231,14,3,230,89,42,85,171,111,20,160,112,216,151,205,99,235,8,12,167,8,115,242,155,136,92,182,60,236,36,149,81,34,181,210,23,247,109,85,125,54,166,38,153,95,143,187,16,181,8,181,33,47,244,133,38,181,123,105,225,181,0,253,101,16,145,53,100,127,163,67,191,191,165,220,81,138,82,79,136,45,43,207,8,118,124,113,95,121,17,104,0,174,95,232,102,16,203,170,65,71,2,217,127,242,141,181,36,214,123,228,123,174,190,127,7,173,94,149,196,100,171,144,116,85,76,177,161,59,38,48,192,147,36,138,210,55,129,216,132,191,211,9,34,93,42,109,216,138,39,116,232,184,135,84,166,168,81,151,186,162,178,144,144,219,174,199,137]}],"Latitude":37.787595185916075,"Longitude":-122.40473812968625,"Accuracy":76.0,"AuthInfo":null,"AuthTicket":{"Start":[24,23,103,255,241,214,159,164,93,167,205,22,23,226,141,217,91,200,215,146,187,220,151,220,230,38,147,154,113,39,185,204,119,86,219,149,153,232,217,109,238,98,57,115,90,248,92,193,55,242,252,121,196,98,93,152,105,199,237,121,212,90,94,189],"ExpireTimestampMs":1488637529457,"End":[181,44,30,252,69,37,235,216,45,150,223,207,54,190,214,131]},"MsSinceLastLocationfix":20169}
[22:15:54] (ERROR)    於 PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() 於 c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs: 行 129

**Comment by slobad008** [comment]
Got something simlilar

[15:47:59] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
[15:47:59] (INFO) Traveling to Pokestop: Your selected location (12 m) (0 seconds) (route Google Walk)
[15:48:02] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[15:48:02] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":823564444,"Requests":[{"RequestType":101,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,52,50,51,53,53,51,55,48,55,50,54,49,48,53,17,201,68,144,123,164,158,64,64,25,228,119,73,23,160,115,96,64,33,255,67,30,214,164,158,64,64,41,0,0,0,204,160,115,96,64]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,159,211,226,221,169,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,99,49,102,50,54,49,49,98,102,57,49,100,48,49,57,102,48,97,54,54,48,101,54,102,51,56,98,48,99,51,97,50,54,97,51,54,98,97,53,48]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,155,184,223,76,120,35,48,74,157,135,97,222,35,183,224,171,68,81,42,134,179,171,78,50,110,190,6,53,159,142,190,134,217,135,130,210,118,42,82,209,80,220,138,236,86,95,45,96,90,225,44,52,117,254,47,199,206,42,222,112,144,247,176,126,115,239,193,70,90,112,181,91,255,253,248,215,32,223,238,133,95,162,124,200,189,19,217,248,191,203,176,189,124,172,3,220,158,75,30,83,17,79,169,167,105,103,251,206,31,128,91,138,98,148,20,203,254,0,254,98,121,234,104,199,183,121,127,50,73,49,11,88,45,95,102,75,47,230,66,188,85,145,75,229,55,160,58,187,156,199,199,143,228,78,115,209,117,107,39,101,198,155,184,173,84,118,153,23,195,82,249,42,169,28,62,115,4,6,136,6,147,88,22,187,107,246,24,9,63,175,128,81,139,26,201,163,248,160,127,0,244,131,86,15,30,193,103,4,78,42,237,207,193,254,254,18,255,197,58,16,22,106,246,183,136,72,57,94,250,143,197,177,174,254,73,221,43,53,246,54,154,98,197,199,54,154,236,32,214,175,122,187,98,55,100,103,122,73,86,111,19,253,102,217,117,141,22,119,37,4,175,127,253,106,177,208,158,183,227,10,43,146,94,21,115,207,50,242,86,214,33,25,88,159,53,26,48,42,19,241,233,229,207,16,158,203,5,153,214,36,20,118,67,68,12,112,154,103,195,172,243,243,125,214,25,57,74,79,163,234,106,7,58,210,54,34,115,10,85,61,168,228,219,70,190,194,234,135,55,7,63,70,131,22,225,123,24,245,90,232,120,199,168,45,197,12,91,208,93,34,191,190,183,82,141,168,227,188,154,116,41,59,186,120,148,26,6,157,49,190,56,99,90,126,86,236,35,165,45,63,198,213,75,45,211,198,99,123,6,216,160,167,89,236,115,100,208,192,56,61,249,165,131,23,239,171,95,138,107,35,145,142,127,199,247,195,14,38,14,67,152,107,229,7,247,95,30,220,163,11,24,85,230,198,105,213,244,229,153,198,207,70,104,250,170,217,165,75,206,185,139,80,156,203,41,103,196,12,42,119,140,76,235,169,209,80,167,65,158,79,65,70,234,79,180,2,211,227,125,54,198,71,150,66,33,18,168,101,140,29,78,134,31,156,78,242,90]}],"Latitude":33.23939461273546,"Longitude":131.61329235410005,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[178,44,141,38,39,159,222,77,204,201,47,115,116,185,74,163,75,76,178,179,106,19,114,35,230,154,11,1,27,181,73,138,198,71,222,115,136,89,227,107,198,237,63,183,100,137,238,203,141,117,177,203,104,1,198,236,118,119,1,168,88,180,71,179,128,59,10,45,89,229,37,203,182,239,40,216,148,203,114,2],"ExpireTimestampMs":1488672592958,"End":[238,213,166,31,217,142,129,10,109,191,87,207,255,231,157,95]},"MsSinceLastLocationfix":23597}
[15:48:02] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<SearchFort>d__2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<FarmPokestop>d__17.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 391
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<DoActionAtPokeStop>d__15.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 101

**Comment by hardknoxni69a** [comment]
attaching #1156 similar exception

**Comment by hardknoxni69a** [comment]
attaching to #1234
