### ISSUE TITLE
chromedriver probleme

### ISSUE THREAD

**Issue by volksboyzz** [Necrobot-Private/NecroBot#1172]
help me plzzz i have this probleme at start bot can work 5 minute after automatical turn down

[08:15:42] (INFO) Your IP is: 174.92.246.48
[08:15:42] (UPDATE) Perfect! You already have the newest Version 1.0.0.132
[08:15:42] (INFO) Logging in using Ptc volksboyzzzz
[08:15:47] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: DownloadRemoteConfigVersion
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__9`7.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Download.<GetRemoteConfigVersion>d__6.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Download.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[08:16:07] (INFO) Logging in using Ptc volksboyzzzz
Starting ChromeDriver 2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9) on port 64198
Only local connections are allowed.
[08:16:10] (ERROR) You didn't resolve captcha in the given time: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 10.0.14393 x86_64)
[08:16:10] (ATTENTION) Captcha is being shown and will need to be solved.
[08:16:10] (ERROR) The bot will now exit after hitting the enter key.
[08:16:12] (INFO) Connecting to ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket ....

**Comment by garette1** [comment]
you must install google chrome.bot will shoe you captcha on chrome and you resolve it.

**Comment by volksboyzz** [comment]
where i can find it ?
