### ISSUE TITLE
Can't use NecroBot!

### ISSUE THREAD

**Issue by StephenSulimani** [Necrobot-Private/NecroBot#1203]
### Expected Behavior:
Supposed to start bot.

### Actual Behavior:
Throws this error and stops.

### Your config.json:
Unnecessary. I tested with a fresh version of Necrobot.

### (OPTIONAL) Your Log:
[20:42:19] (INFO) Connecting to ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket ....
[20:42:19] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__4`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

### Detailed Steps to Reproduce:
Open Necrobot2

Version: 1.0.0.133
Windows Version: Windows 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): You can't use the bot.

**Comment by jjskuld** [comment]
New API is forced, so bot is down. See discord announcements.
