### ISSUE TITLE
I cant log in by using my google account

### ISSUE THREAD

**Issue by zsw12abc** [Necrobot-Private/NecroBot#1207]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Expected Behavior:
I just try to log in my account and it works prefect 1 hour ago. And I didn't change anything.

### Actual Behavior:
But I cant log into my google account . I can play it on my phone but not by using the bot.
The bot stuck at bot switching account processing......

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
[13:29:59] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\JK\workspace\necrobot-release\FeroxRev\Extensions\HttpClientExtensions.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__4`2.MoveNext() in C:\JK\workspace\necrobot-release\FeroxRev\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in C:\JK\workspace\necrobot-release\FeroxRev\Rpc\Player.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in C:\JK\workspace\necrobot-release\FeroxRev\Rpc\Login.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext() in C:\JK\workspace\necrobot-release\PoGo.NecroBot.Logic\State\LoginState.cs:line 55
[13:30:04] (INFO) Connecting to ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket ....```

### Detailed Steps to Reproduce:


### Other Information
(Attach zip files if needed.)


Version: 1.0.0.133
Windows Version: win10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by StephenSulimani** [comment]
I'm assuming this is because of the API Update. Check Discord.

**Comment by pkmjmguillen** [comment]
i can't login too... what is supposed to be the problem? TIA

**Comment by zsw12abc** [comment]
They said the API Update killed this program.
So when will they fix it?

**Comment by StephenSulimani** [comment]
I don't know. The developer seems to be working vigorously.

**Comment by zsw12abc** [comment]
I tried the new version which is v1.0.0.134 
however still the same problem.
I try the new account and new folder still the same.

**Comment by Jitm92** [comment]
Facing the same issue here.

**Comment by hardknoxni69a** [comment]
please consider spending the 4$ as niantic is trying to kill v.45 and we are running out of work arounds obviously we will keep trying but we can only do so much the hashing server is working great we will keep you guys updated in the discord come on by and we will get an update as soon as possible

**Comment by LEE-BC** [comment]
excellent~~!!
hardknoxni69a
