### ISSUE TITLE
Bot Fails when attacking an opponent Gym

### ISSUE THREAD

**Issue by asindkhu** [Necrobot-Private/NecroBot#1228]
[23:28:20] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[23:28:21] (ERROR) Error: System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Hash\PokefamerHasher.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(RequestEnvelope requestEnvelope, GeoCoordinate currentLocation) in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Helpers\RequestBuilder.cs:line 204
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Helpers\RequestBuilder.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<GetFort>d__1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\Fort.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Hash\PokefamerHasher.cs:line 48<---

It goes on and on like this. On latest version and using a Hash key

**Comment by GottaPeachEmAll** [comment]
i have the same problem. i asked 3 devs... still no answer

**Comment by hardknoxni69a** [comment]
gym is still beta guys please disable if you would like or do manually give it some time guys as gym botting is extremely complex

**Comment by gitnotoff** [comment]
Same here. I used latest version and using a Hashkey.
I closed bot, waited some hours and started pokemon on my phone.
->->-> A warning was displayed !!!
It says: They noticed that my account is using modified Client-Software or 3rd party software.
This is not legit. They recommend not to use such software.
I closed this warning and game worked as always on phone.

Perhaps we should stop botting for some days...

**Comment by cocacolabanane** [comment]
server down ??

**Comment by vertil** [comment]
seems like, yes: http://pokehash.buddyauth.com/

**Comment by cocacolabanane** [comment]
13:08:39] () Configuration is up-to-date. Schema version: 20
[13:08:40] () Validating config.json...
[13:08:40] () Auth Configuration is up-to-date. Schema version: 20
[13:08:40] () Validating auth.json...
[13:08:42] (FEHLER) Counld't start socket server at port 14251, this port maybe in use or block, please change config to other port and restart bot if you want to use web gui.
[13:08:42] (INFO) Switching to affen02...
[13:08:42] (INFO) affen02 (Level: 21)			Runtime : 00:00:00:00

**Comment by cocacolabanane** [comment]
[13:15:19] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:15:19] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:15:19] (FEHLER) Hash API server down time : 00:00:00   Last ping: 1:15:19 PM
[13:15:24] (FEHLER) Hash API server down time : 00:00:05   Last ping: 1:15:24 PM
[13:15:29] (FEHLER) Hash API server down time : 00:00:10   Last ping: 1:15:29 PM
[13:15:34] (FEHLER) Hash API server down time : 00:00:15   Last ping: 1:15:34 PM
[13:15:39] (FEHLER) Hash API server down time : 00:00:20   Last ping: 1:15:39 PM
[13:15:44] (FEHLER) Hash API server down time : 00:00:25   Last ping: 1:15:44 PM
[13:15:49] (FEHLER) Hash API server down time : 00:00:30   Last ping: 1:15:49 PM
[13:15:55] (FEHLER) Hash API server down time : 00:00:35   Last ping: 1:15:55 PM

**Comment by cocacolabanane** [comment]
[13:28:17] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:17] (INFO) Einloggen mit Ptc
[13:28:17] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:17] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:18] (INFO) Einloggen mit Ptc
[13:28:18] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:18] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:18] (INFO) Einloggen mit Ptc
[13:28:18] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:18] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:18] (INFO) Einloggen mit Ptc
[13:28:18] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:18] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:18] (INFO) Einloggen mit Ptc
[13:28:18] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:18] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:18] (INFO) Einloggen mit Ptc
[13:28:19] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:19] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:19] (INFO) Einloggen mit Ptc
[13:28:19] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:19] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:19] (INFO) Einloggen mit Ptc
[13:28:19] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:19] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:19] (INFO) Einloggen mit Ptc
[13:28:19] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:19] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:19] (INFO) Einloggen mit Ptc
[13:28:20] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:20] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:20] (INFO) Einloggen mit Ptc
[13:28:20] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:20] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:20] (INFO) Einloggen mit Ptc
[13:28:20] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:20] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:20] (INFO) Einloggen mit Ptc
[13:28:20] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:20] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:21] (INFO) Einloggen mit Ptc
[13:28:21] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:21] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:21] (INFO) Einloggen mit Ptc
[13:28:21] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:21] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:21] (INFO) Einloggen mit Ptc
[13:28:21] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:21] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:21] (INFO) Einloggen mit Ptc
[13:28:22] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:22] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:22] (INFO) Einloggen mit Ptc
[13:28:22] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:22] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:22] (INFO) Einloggen mit Ptc
[13:28:22] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:22] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:23] (INFO) Einloggen mit Ptc
[13:28:23] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:23] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:23] (INFO) Einloggen mit Ptc
[13:28:23] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:23] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:23] (INFO) Einloggen mit Ptc
[13:28:23] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:23] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:24] (INFO) Einloggen mit Ptc
[13:28:24] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:24] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:24] (INFO) Einloggen mit Ptc
[13:28:24] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[13:28:24] (ACHTUNG) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[13:28:24] (INFO) Einloggen mit Ptc
[13:28:24] (FEHLER) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!

**Comment by hardknoxni69a** [comment]
Please note all users are not receiving this message so you may need to adjust your settings to avoid getting your account flagged remember safety first

**Comment by ziomber** [comment]
I was doing most of gym changes since last month but this error is not connected with gym code. This is some issue with the API or so.

**Comment by asindkhu** [comment]
19:08:00] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[19:08:00] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext()

in the middle of gym battle..

**Comment by Lord-Haji** [comment]
#1251
