### ISSUE TITLE
Weird Errors

### ISSUE THREAD

**Issue by TaylorZaneKirk** [Necrobot-Private/NecroBot#1234]
I got similar errors within a couple of hours of each other. Botting in the same place, no sniping or gyms or item usage. Will post both error logs.

FIRST:
```
[10:22:33] (ERROR) Error: System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Hash\PokefamerHasher.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(RequestEnvelope requestEnvelope, GeoCoordinate currentLocation) in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Helpers\RequestBuilder.cs:line 204
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Helpers\RequestBuilder.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__12.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\Map.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<GetNearbyPokemons>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<OnWalkingToPokeStopOrGym>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass11_0.<<WalkingToPokeStop>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Strategies.Walk.BaseWalkStrategy.<DoWalk>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Navigation.<Move>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Hash\PokefamerHasher.cs:line 48<---
```
SECOND:
```
[11:50:46] (ERROR) Error: System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST 
{"StatusCode":2,"RequestId":1061382639,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,52,55,52,50,49,50,52,51,49,52,50,57,54,50,17,163,122,231,61,35,1,65,64,25,33,200,134,6,212,159,93,192,33,214,169,242,61,35,1,65,64,41,195,241,124,6,212,159,93,192]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,247,154,224,202,171,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,51,51,48,54,55,51,57,57,53,54,52,55,101,98,57,51,98,57,49,50,101,98,57,97,53,52,48,48,50,53,100,48,57,48,57,100,98,100,101,101]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,185,58,173,220,85,80,149,97,180,215,220,68,193,112,234,164,178,101,190,28,170,65,220,244,47,81,30,174,98,212,6,221,76,35,204,13,16,103,3,65,91,242,224,135,116,27,10,91,149,241,214,72,35,39,237,151,20,129,87,190,95,150,181,247,163,60,16,58,234,0,129,225,187,239,112,112,108,57,12,158,103,108,255,135,184,168,186,123,240,235,185,80,150,46,57,155,152,169,129,231,161,153,124,89,243,47,163,179,212,151,94,11,250,19,213,175,193,65,115,150,84,244,8,170,93,129,137,123,20,237,17,9,217,99,198,246,47,148,245,126,139,198,178,148,217,254,183,195,6,105,237,148,180,234,176,99,47,167,7,39,14,39,92,231,229,227,175,173,164,209,227,72,137,28,158,82,15,231,139,7,35,13,17,76,88,44,91,33,31,163,192,53,75,188,164,249,2,98,79,69,201,37,207,98,130,228,59,56,14,181,45,2,57,31,35,39,99,8,81,29,85,112,100,37,202,239,103,128,55,141,253,57,124,125,234,191,155,181,181,73,141,212,138,192,229,54,65,217,52,15,124,226,127,84,69,145,241,132,92,163,58,206,226,158,142,246,168,196,12,157,182,166,172,139,119,220,16,145,116,161,118,77,26,192,27,189,18,233,252,97,73,85,92,202,87,77,111,45,116,185,247,95,65,107,136,191,140,16,40,55,66,188,39,125,4,103,3,54,68,194,87,138,134,51,182,37,105,241,177,180,114,121,237,228,180,118,189,86,91,59,177,91,73,220,19,116,159,174,63,13,132,44,109,67,121,92,73,253,26,179,0,157,174,145,127,62,228,221,40,1,245,213,244,203,81,102,115,207,69,121,167,208,50,27,242,196,59,42,155,37,118,130,5,163,62,74,69,242,151,96,238,209,200,73,219,93,243,234,7,125,15,76,160,47,54,144,98,228,237,85,191,40,48,170,57,204,124,247,176,69,83,56,231,76,7,255,134,194,4,235,136,157,184,154,98,114,87,95,187,58,253,246,84,162,9,223,69,116,108,5,151,254,56,206,152,180,217,254,200,130,87,52,107,215,157,188,167,254,98,105,150,28,39,13,181,51,140,125,9,126,100,252,154,246,125,3,18,223,104,180,66,202,241,41,249,101,152,50,38,101,171,190,65,226,68,94,146]}],"Latitude":34.00888799479187,"Longitude":-118.49731600916176,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[11,72,97,248,131,75,16,56,128,21,60,20,14,123,83,188,56,148,25,240,110,39,23,174,104,249,189,81,51,3,179,33,180,16,109,176,165,183,54,125,107,200,68,43,246,19,255,234,31,85,97,24,132,91,28,193,13,45,176,218,208,221,91,28,115,234,37,120,225,58,95,150,156,249,82,226,60,0,112,187],"ExpireTimestampMs":1489169920421,"End":[27,104,25,76,251,49,36,233,67,255,255,224,232,49,63,6]},"MsSinceLastLocationfix":21329}
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Extensions\HttpClientExtensions.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Extensions\HttpClientExtensions.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\Fort.cs:line 266
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PoGo.NecroBot.Logic.State.CachedGymGetails.LoadData(ISession session, FortData fort)
   at PoGo.NecroBot.Logic.State.CachedGymGetails..ctor(ISession session, FortData fort)
   at PoGo.NecroBot.Logic.State.GymTeamState.getGymDetails(ISession session, FortData fort, Boolean force)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST 
{"StatusCode":2,"RequestId":1061382639,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,52,55,52,50,49,50,52,51,49,52,50,57,54,50,17,163,122,231,61,35,1,65,64,25,33,200,134,6,212,159,93,192,33,214,169,242,61,35,1,65,64,41,195,241,124,6,212,159,93,192]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,247,154,224,202,171,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,51,51,48,54,55,51,57,57,53,54,52,55,101,98,57,51,98,57,49,50,101,98,57,97,53,52,48,48,50,53,100,48,57,48,57,100,98,100,101,101]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,185,58,173,220,85,80,149,97,180,215,220,68,193,112,234,164,178,101,190,28,170,65,220,244,47,81,30,174,98,212,6,221,76,35,204,13,16,103,3,65,91,242,224,135,116,27,10,91,149,241,214,72,35,39,237,151,20,129,87,190,95,150,181,247,163,60,16,58,234,0,129,225,187,239,112,112,108,57,12,158,103,108,255,135,184,168,186,123,240,235,185,80,150,46,57,155,152,169,129,231,161,153,124,89,243,47,163,179,212,151,94,11,250,19,213,175,193,65,115,150,84,244,8,170,93,129,137,123,20,237,17,9,217,99,198,246,47,148,245,126,139,198,178,148,217,254,183,195,6,105,237,148,180,234,176,99,47,167,7,39,14,39,92,231,229,227,175,173,164,209,227,72,137,28,158,82,15,231,139,7,35,13,17,76,88,44,91,33,31,163,192,53,75,188,164,249,2,98,79,69,201,37,207,98,130,228,59,56,14,181,45,2,57,31,35,39,99,8,81,29,85,112,100,37,202,239,103,128,55,141,253,57,124,125,234,191,155,181,181,73,141,212,138,192,229,54,65,217,52,15,124,226,127,84,69,145,241,132,92,163,58,206,226,158,142,246,168,196,12,157,182,166,172,139,119,220,16,145,116,161,118,77,26,192,27,189,18,233,252,97,73,85,92,202,87,77,111,45,116,185,247,95,65,107,136,191,140,16,40,55,66,188,39,125,4,103,3,54,68,194,87,138,134,51,182,37,105,241,177,180,114,121,237,228,180,118,189,86,91,59,177,91,73,220,19,116,159,174,63,13,132,44,109,67,121,92,73,253,26,179,0,157,174,145,127,62,228,221,40,1,245,213,244,203,81,102,115,207,69,121,167,208,50,27,242,196,59,42,155,37,118,130,5,163,62,74,69,242,151,96,238,209,200,73,219,93,243,234,7,125,15,76,160,47,54,144,98,228,237,85,191,40,48,170,57,204,124,247,176,69,83,56,231,76,7,255,134,194,4,235,136,157,184,154,98,114,87,95,187,58,253,246,84,162,9,223,69,116,108,5,151,254,56,206,152,180,217,254,200,130,87,52,107,215,157,188,167,254,98,105,150,28,39,13,181,51,140,125,9,126,100,252,154,246,125,3,18,223,104,180,66,202,241,41,249,101,152,50,38,101,171,190,65,226,68,94,146]}],"Latitude":34.00888799479187,"Longitude":-118.49731600916176,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[11,72,97,248,131,75,16,56,128,21,60,20,14,123,83,188,56,148,25,240,110,39,23,174,104,249,189,81,51,3,179,33,180,16,109,176,165,183,54,125,107,200,68,43,246,19,255,234,31,85,97,24,132,91,28,193,13,45,176,218,208,221,91,28,115,234,37,120,225,58,95,150,156,249,82,226,60,0,112,187],"ExpireTimestampMs":1489169920421,"End":[27,104,25,76,251,49,36,233,67,255,255,224,232,49,63,6]},"MsSinceLastLocationfix":21329}
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Extensions\HttpClientExtensions.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Extensions\HttpClientExtensions.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\Fort.cs:line 266<---
```

Only one thing worthy of note: I do usually "micro-manage" my bot (I live in a rural area, so it's about as close as I can get to playing). As such, I always tell the bot to "catch this pokemon" or "travel here." Maybe errors arise when the pokemon it was sent to catch despawns? I'm really just guessing, though.

**Comment by hardknoxni69a** [comment]
first error is hash server connection. other error could be connected to other issue about requests

**Comment by hardknoxni69a** [comment]
Attaching #1162 for Bad Requests

**Comment by jjskuld** [comment]
We have confirmation from Bossland that there exists a bug in the hash server regarding session invalidations -  "only existing issue right now is SessionInvalidated caused by wrong rounding done by hash servers"

So waiting for a fix.
