### ISSUE TITLE
Latest 32 Bit Version 1.35 does not work

### ISSUE THREAD

**Issue by mboeder** [Necrobot-Private/NecroBot#1246]
Tried to to update to latest Version, but it does not work. Starting prompt stops on validatiing auth.json.

LOG:

[18:32:39] () Configuration is up-to-date. Schema version: 20
[18:32:39] () Validating config.json...
[18:32:40] () Auth Configuration is up-to-date. Schema version: 20
[18:32:40] () Validating auth.json...

Version:
Windows Version: 7 32 Bit

**Comment by JimN-Syd** [comment]
I'm getting exactly the same on the 64 bit version, running on Windows 2008 R2 Server. Works fine for me on Windows 10, Although on machines where it works, the line after Validating auth-json has changed from:

(INFO) Websocket listening on at  wss://localhost:14251 or ws://localhost:14252 

to 

(ERROR) Failed to start WebSocketServer on port : 14251

for me.

**Comment by Lord-Haji** [comment]
Ur port 14251 Is blocked try another

**Comment by hardknoxni69a** [comment]
Please Read The Announcements In Discord Or The ChangeLog Under 135 From Now On Microsoft .NET 4.6.2 Is Required. As A Software Provider We Strive To Bring You Guys The Best Products And That Requires Updating Your .NET Please Check The Link Under The Download Or Feel Free To Google Once You Have Updated You Will Be On And Rocking

**Comment by mboeder** [comment]
@hardknoxni69a i am running microsoft.net version 4.6.2 on my windows 7 32 Bit OS. Still latest 32 Bit Version does not work. 

[19:23:36] () Configuration is up-to-date. Schema version: 20
[19:23:36] () Validating config.json...
[19:23:36] () Auth Configuration is up-to-date. Schema version: 20
[19:23:36] () Validating auth.json...
[19:23:37] () [ERROR] Issue loading translations: Newtonsoft.Json.JsonSerializationException: Error converting value "ho-Oh" to type 'POGOProtos.Enums.PokemonId'. Path 'PokemonStrings[249].Key', line 1590, position 21. ---> System.ArgumentException: Requested value 'ho-Oh' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PoGo.NecroBot.Logic.Common.Translation.Load(ILogicSettings logicSettings, Translation translations) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\Common\Translations.cs:line 1836
[19:23:37] () [Request] Rebuild the translations folder? Y/N

Pressing Y ist not possible in WiN Version. Using console is working, after confirming rebuild. I tried to rebuild with console and then start window Version, but same error occurs. Even console version always starts with same "rebuild" issue. What am i doing wrong?

**Comment by hardknoxni69a** [comment]
Well u need to read the warning it says ho-oh is not valid u need to put
hooh

**Comment by hardknoxni69a** [comment]
Also on WIN u click show console and u can use console while in WIN to type
ur responses
