### ISSUE TITLE
NecroBot2.WIN.32Bit & NecroBot2.WIN

### ISSUE THREAD

**Issue by TheWizard1328** [Necrobot-Private/NecroBot#1275]
Hello,
I am a coder and have been working on an app that tracks(manually) my Pokemon stats. For now it is all manual. It just shows me how many Pokemon I have and which ones I can evolve. It shows a bit more info for me but what I have done is integrate code to read your logs files and extract the info I need to update my data files.

But when it comes to hatching eggs, there is no info in your log files about Egg size, Stardust earned & candies earned. This would be useful info like all the other info you log on everything else in app.

Same goes for the Pokemon upgrade/Power-ups. There is nothing in app that really distinguished these lines from other lines and no info relating to Stardust & candies used to Power-Up.

Hope this info can be integrated into your next update.

Thanks,

The Wizard.
### (OPTIONAL) Your Log:
[13:34:41] (EGG) Incubated egg has hatched: Rhyhorn | Lvl: 20 CP: (945/1680) IV: 88.89%
[13:38:23] (EGG) Incubated egg has hatched: Psyduck | Lvl: 20 CP: (540/967) IV: 88.89%
[13:38:23] (EGG) Incubated egg has hatched: Psyduck | Lvl: 20 CP: (526/967) IV: 82.22%
[13:54:28] (EGG) Incubated egg has hatched: NidoranMale | Lvl: 20 CP: (401/740) IV: 84.44%
[14:54:27] (EGG) Incubated egg has hatched: Geodude | Lvl: 20 CP: (647/1194) IV: 80%
[15:06:10] (EGG) Incubated egg has hatched: Voltorb | Lvl: 20 CP: (460/857) IV: 77.78%
[15:06:10] (EGG) Incubated egg has hatched: Drowzee | Lvl: 20 CP: (535/993) IV: 77.78%
[15:06:10] (EGG) Incubated egg has hatched: Exeggcute | Lvl: 20 CP: (601/1102) IV: 82.22%

Version: your Latest version
Windows Version: Windows 10
What is affected (evolve, powerup/levelup, Hatching Eggs):

**Comment by Lord-Haji** [comment]
Feel free to fix this

**Comment by hardknoxni69a** [comment]
open source feel free to make the neccessary changes bud always looking for coders to help out project as its a free project and not many devs chipping in

**Comment by TheWizard1328** [comment]
I have tried to download the source code but keeps saying there’s missing items.

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by TheWizard1328** [comment]
This is the messages I keep getting when I try to load the source code.

D:\Users\Robert\Documents\NecRobot2\NecroBot-1.0.0.139-Source Code\NecroBot-1.0.0.139\FeroxRev\PokemonGo.RocketAPI.csproj
error  : The project file could not be loaded. Could not find file 'D:\Users\Robert\Documents\NecRobot2\NecroBot-1.0.0.139-Source Code\NecroBot-1.0.0.139\FeroxRev\PokemonGo.RocketAPI.csproj'.  D:\Users\Robert\Documents\NecRobot2\NecroBot-1.0.0.139-Source Code\NecroBot-1.0.0.139\FeroxRev\PokemonGo.RocketAPI.csproj

D:\Users\Robert\Documents\NecRobot2\NecroBot-1.0.0.139-Source Code\NecroBot-1.0.0.139\POGOProtos\POGOProtos.csproj
error  : The project file could not be loaded. Could not find file
'D:\Users\Robert\Documents\NecRobot2\NecroBot-1.0.0.139-Source Code\NecroBot-1.0.0.139\POGOProtos\POGOProtos.csproj'.  D:\Users\Robert\Documents\NecRobot2\NecroBot-1.0.0.139-Source Code\NecroBot-1.0.0.139\POGOProtos\POGOProtos.csproj

These folders are empty, FeroxRev & POGOProtos.

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by jjskuld** [comment]
@TheWizard1328 Those are submodules, which means you need to clone recursively.

```
git clone --recursive https://github.com/Necrobot-Private/NecroBot.git
```

Or if you already cloned, you can grab submodules using

```
git submodule update --init --recursive
```

**Comment by TheWizard1328** [comment]
So this may sound like a dumb question, but what changes were made from 1.0.0.139 and 1.0.0.143.
Would you be interested in seeing some of the code for the additions I’ve made?

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by hardknoxni69a** [comment]
We are always open to changes you can submit a pull request for the changes you've done to your branch or get a hold of me on discord but yes interested

**Comment by TheWizard1328** [comment]
Thought you might be interested in his error code that keeps popping in my log files.

[23:41:55] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[23:41:55] (ERROR) Error: System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST
{"StatusCode":2,"RequestId":2007237711,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,53,57,48,57,48,48,56,56,51,50,56,50,52,52,17,235,98,7,204,111,193,74,64,25,0,0,0,8,70,104,92,192,33,235,98,7,204,111,193,74,64,41,0,0,0,8,70,104,92,192]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,200,179,212,246,175,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,51,97,51,48,97,54,98,54,49,48,97,51,101,57,97,101,48,101,100,98,49,97,51,99,101,102,57,101,54,100,57,52,53,56,56,102,100,50,100,50]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,97,53,52,97,49,98,50,57,53,97,52,51,57,100,52,51,49,101,102,48,49,100,50,56,102,56,56,55,52,51,51,50,49,52,56,54,100,55,54,52]},{"Type":6,"RequestMessage":[10,133,4,254,213,73,233,43,118,137,155,39,227,133,157,175,92,217,151,141,112,147,144,99,159,138,180,183,244,156,59,87,166,96,104,100,126,247,59,120,86,22,156,137,175,223,37,32,64,84,82,69,217,144,146,226,19,226,147,213,35,3,106,250,229,104,188,202,0,49,78,117,77,251,255,62,216,7,170,0,161,1,218,109,0,50,38,124,88,242,164,129,156,74,55,73,219,68,196,118,217,116,249,150,154,119,70,222,46,15,219,58,161,189,242,60,201,7,26,137,64,168,220,136,57,191,65,153,70,11,54,72,125,113,174,6,28,106,128,91,58,201,178,95,88,171,93,140,78,121,74,16,110,98,98,48,102,42,24,11,161,176,230,41,211,69,198,105,237,245,64,216,66,112,211,16,220,182,201,90,245,245,5,169,100,129,86,111,179,189,70,234,161,197,236,96,163,205,41,186,130,117,62,176,220,36,47,234,193,199,93,226,83,88,244,72,49,23,38,183,240,58,186,239,88,143,0,82,212,196,240,206,57,120,37,74,53,134,24,208,53,24,0,133,92,144,228,126,28,236,134,232,193,122,118,110,164,155,157,246,253,96,113,11,245,190,90,78,130,176,123,200,192,155,184,73,117,190,161,7,28,238,1,5,247,147,37,67,89,210,252,202,172,173,107,203,182,17,30,73,95,244,218,127,238,218,78,246,74,34,208,224,54,64,84,166,55,181,40,224,157,254,102,231,173,80,212,173,38,109,178,134,162,5,55,55,32,23,167,236,106,172,255,25,231,48,2,30,184,238,206,212,163,135,218,208,247,164,113,73,41,24,91,80,124,170,52,255,9,62,226,30,48,43,149,156,10,200,99,7,255,2,206,68,38,53,50,249,173,150,7,67,3,70,206,255,27,193,14,55,222,162,88,172,214,215,91,28,104,154,171,184,28,253,114,109,136,224,27,157,75,93,17,50,121,181,86,52,183,28,106,173,129,26,48,71,33,19,57,170,146,39,70,25,162,79,122,102,91,47,54,228,13,125,80,145,174,231,253,171,53,10,113,143,170,203,19,184,234,107,88,182,116,56,219,139,218,219,127,1,148,44,152,76,90,236,8,238,72,146,62,112,19,129,179,150,120,37,59,199,10,185,87,230,133,240,38,16,59,206,130,51,84,46,194,133,227,44,162,115]}],"Latitude":53.51122,"Longitude":-113.62927,"Accuracy":65.0,"AuthInfo":null,"AuthTicket":{"Start":[193,76,85,240,59,56,223,226,98,220,96,4,102,112,106,119,252,219,32,192,9,36,47,18,75,149,154,29,162,102,84,138,178,246,144,38,126,191,252,47,252,198,215,198,149,145,35,142,78,99,26,244,233,55,50,168,32,39,174,251,2,166,80,229],"ExpireTimestampMs":1490335884185,"End":[168,196,176,47,83,148,176,88,237,76,236,0,145,111,19,218]},"MsSinceLastLocationfix":5748}
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Extensions\HttpClientExtensions.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Extensions\HttpClientExtensions.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Rpc\Fort.cs:line 266
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PoGo.NecroBot.Logic.State.CachedGymGetails.LoadData(ISession session, FortData fort) in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\PoGo.NecroBot.Logic\State\GymTeamState.cs:line 279
   at PoGo.NecroBot.Logic.State.CachedGymGetails..ctor(ISession session, FortData fort) in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\PoGo.NecroBot.Logic\State\GymTeamState.cs:line 273
   at PoGo.NecroBot.Logic.State.GymTeamState.getGymDetails(ISession session, FortData fort, Boolean force) in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\PoGo.NecroBot.Logic\State\GymTeamState.cs:line 92
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\PoGo.NecroBot.Logic\State\FarmState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:line 116
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST
{"StatusCode":2,"RequestId":2007237711,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,53,57,48,57,48,48,56,56,51,50,56,50,52,52,17,235,98,7,204,111,193,74,64,25,0,0,0,8,70,104,92,192,33,235,98,7,204,111,193,74,64,41,0,0,0,8,70,104,92,192]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,200,179,212,246,175,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,51,97,51,48,97,54,98,54,49,48,97,51,101,57,97,101,48,101,100,98,49,97,51,99,101,102,57,101,54,100,57,52,53,56,56,102,100,50,100,50]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,97,53,52,97,49,98,50,57,53,97,52,51,57,100,52,51,49,101,102,48,49,100,50,56,102,56,56,55,52,51,51,50,49,52,56,54,100,55,54,52]},{"Type":6,"RequestMessage":[10,133,4,254,213,73,233,43,118,137,155,39,227,133,157,175,92,217,151,141,112,147,144,99,159,138,180,183,244,156,59,87,166,96,104,100,126,247,59,120,86,22,156,137,175,223,37,32,64,84,82,69,217,144,146,226,19,226,147,213,35,3,106,250,229,104,188,202,0,49,78,117,77,251,255,62,216,7,170,0,161,1,218,109,0,50,38,124,88,242,164,129,156,74,55,73,219,68,196,118,217,116,249,150,154,119,70,222,46,15,219,58,161,189,242,60,201,7,26,137,64,168,220,136,57,191,65,153,70,11,54,72,125,113,174,6,28,106,128,91,58,201,178,95,88,171,93,140,78,121,74,16,110,98,98,48,102,42,24,11,161,176,230,41,211,69,198,105,237,245,64,216,66,112,211,16,220,182,201,90,245,245,5,169,100,129,86,111,179,189,70,234,161,197,236,96,163,205,41,186,130,117,62,176,220,36,47,234,193,199,93,226,83,88,244,72,49,23,38,183,240,58,186,239,88,143,0,82,212,196,240,206,57,120,37,74,53,134,24,208,53,24,0,133,92,144,228,126,28,236,134,232,193,122,118,110,164,155,157,246,253,96,113,11,245,190,90,78,130,176,123,200,192,155,184,73,117,190,161,7,28,238,1,5,247,147,37,67,89,210,252,202,172,173,107,203,182,17,30,73,95,244,218,127,238,218,78,246,74,34,208,224,54,64,84,166,55,181,40,224,157,254,102,231,173,80,212,173,38,109,178,134,162,5,55,55,32,23,167,236,106,172,255,25,231,48,2,30,184,238,206,212,163,135,218,208,247,164,113,73,41,24,91,80,124,170,52,255,9,62,226,30,48,43,149,156,10,200,99,7,255,2,206,68,38,53,50,249,173,150,7,67,3,70,206,255,27,193,14,55,222,162,88,172,214,215,91,28,104,154,171,184,28,253,114,109,136,224,27,157,75,93,17,50,121,181,86,52,183,28,106,173,129,26,48,71,33,19,57,170,146,39,70,25,162,79,122,102,91,47,54,228,13,125,80,145,174,231,253,171,53,10,113,143,170,203,19,184,234,107,88,182,116,56,219,139,218,219,127,1,148,44,152,76,90,236,8,238,72,146,62,112,19,129,179,150,120,37,59,199,10,185,87,230,133,240,38,16,59,206,130,51,84,46,194,133,227,44,162,115]}],"Latitude":53.51122,"Longitude":-113.62927,"Accuracy":65.0,"AuthInfo":null,"AuthTicket":{"Start":[193,76,85,240,59,56,223,226,98,220,96,4,102,112,106,119,252,219,32,192,9,36,47,18,75,149,154,29,162,102,84,138,178,246,144,38,126,191,252,47,252,198,215,198,149,145,35,142,78,99,26,244,233,55,50,168,32,39,174,251,2,166,80,229],"ExpireTimestampMs":1490335884185,"End":[168,196,176,47,83,148,176,88,237,76,236,0,145,111,19,218]},"MsSinceLastLocationfix":5748}
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Extensions\HttpClientExtensions.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Extensions\HttpClientExtensions.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() in D:\Users\Robert\Documents\NecRobot2\NecroBot-master source Code\NecroBot-master\FeroxRev\Rpc\Fort.cs:line 266<---

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13
