### ISSUE TITLE
PLS HELP! System.MissingMethodException: Method not found???

### ISSUE THREAD

**Issue by SamMenary** [Necrobot-Private/NecroBot#1288]
Every time I try to log in with my API Hash (that I purchased), I receive this error - Across several accounts:

[03:22:05] (INFO) System.MissingMethodException: Method not found: '!!0[] System
.Array.Empty()'.
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine
](TStateMachine& stateMachine)
   at PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in C:\Users\VAPORS
S\Documents\NecroBot\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

Please help a brother out

**Comment by hardknoxni69a** [comment]
New Release Coming Now Should Fix Let Me Know In A Little Bit

**Comment by SamMenary** [comment]
Same result :(

**Comment by Lord-Haji** [comment]
Delete all the files. 
Download them and start the bot from the scratch :D

**Comment by hardknoxni69a** [comment]
Remember when deleting everything to atleast save ur sessionstats don't want to cause catchflees
