### ISSUE TITLE
Hash server being down, Bot will enter IDLE state until service available. 

### ISSUE THREAD

**Issue by Supergod99** [Necrobot-Private/NecroBot#1338]
Got this error randomly, only bought the API a few days ago. Continually loops after logging into my account
Error code is as follows : 

[22:41:14] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 43.6533016487573 Lng: -79.3831776465145
[22:41:14] (ATTENTION) Without a Google Api, you will have 2500 free quota limit, if you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key
[22:41:18] (ERROR) Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
[22:41:18] (ATTENTION) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...
[22:41:18] (ERROR) Hash API server down time : 00:00:00   Last ping: 22:41:18
[22:41:23] (ERROR) Hash API server down time : 00:00:05   Last ping: 22:41:23
[22:41:28] (ERROR) Hash API server down time : 00:00:10   Last ping: 22:41:28
[22:41:33] (INFO) Connecting to ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket ....
[22:41:34] (INFO) Logging in using Google pokemongo61829
[22:41:35] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[22:41:55] (INFO) Logging in using Google pokemongo61829
[22:41:56] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[22:42:16] (INFO) Logging in using Google pokemongo61829
[22:42:18] (INFO) (HASH SERVER) Key[3O8PXXXXXXXXXXXX2Z3Q] Last 1 minute  3 request/min , AVG: 639.00 ms/request , Fastest : 190, Slowest: 764, Available 99.33%
[22:42:18] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[22:42:38] (INFO) Logging in using Google pokemongo61829
[22:42:39] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[22:42:59] (INFO) Logging in using Google pokemongo61829
[22:43:01] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[22:43:21] (INFO) Logging in using Google pokemongo61829
[22:43:22] (INFO) (HASH SERVER) Key[3O8PXXXXXXXXXXXX2Z3Q] Last 1 minute  3 request/min , AVG: 561.00 ms/request , Fastest : 190, Slowest: 764, Available 99.33%
[22:43:22] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[22:43:42] (INFO) Logging in using Google pokemongo61829
[22:43:43] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[22:44:03] (INFO) Logging in using Google pokemongo61829
[22:44:04] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v127_4/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
 

Version: 1.0.0.144
Windows Version: Windows 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): runtime

**Comment by Lord-Haji** [comment]
@Supergod99 The Bot doesn't want to waste any time. So it is trying to connect again and again

**Comment by Supergod99** [comment]
But why is it disconnected in the first place?

**Comment by hardknoxni69a** [comment]
Necrobot and the hash server are 2 different thing you will have to ask hash server why they are down alot it drives everyone crazy
