### ISSUE TITLE
Issue with starting up bot

### ISSUE THREAD

**Issue by Swampy13** [Necrobot-Private/NecroBot#1351]
I get this error whenever I start up the bot:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by Lord-Haji** [comment]
Internet connection issue:P
