### ISSUE TITLE
Issue) SessionStats.db Bug

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#1390]
This Isnt The First TIme This Has Happened Causes Loop And Doesnt Fix Unless You Delete Your SessionStats Which Mean No Botting Basically For Atleast 24 Hours Comes Out Of NoWhere

[01:22:02] (POKESTOP) Name: State House Balcony XP: 100, Gems: 0, Items: 2 x ItemPokeBall, 2 x ItemGreatBall, 1 x ItemRazzBerry, 1 x ItemRevive, Lat: 42.358546, Long: -71.06432, Alt: 12.821968050125
[01:22:03] (INFO) (POKESTOP LIMIT) 994/1961
[01:22:06] (INFO) Traveling to Pokestop: Church of the Larger Fellowship  (69 m) (2 seconds) (route NecroBot Walk)
[01:22:14] (POKESTOP) Name: Church of the Larger Fellowship  XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemUltraBall, 1 x ItemPotion, Lat: 42.357956, Long: -71.064562, Alt: 7.58056693597723
[01:22:15] (INFO) (POKESTOP LIMIT) 995/1966
[01:22:17] (INFO) Traveling to Pokestop: Appalachian Mountain Club (50 m) (2 seconds) (route NecroBot Walk)
[01:22:32] (INFO) (HASH SERVER) Key[0P3IXXXXXXXXXXXX8I1C] Last 1 minute  19 request/min , AVG: 437.00 ms/request , Fastest : 394, Slowest: 1409, Available 98.67%
[01:22:35] (INFO) (CATCH LIMIT) 848/974
[01:22:36] (PKMN) (CatchSuccess) | (Normal) Weedle Lvl: 4 CP: (37/397) IV: 67.00% | Chance: 99.28% | 0.00m dist | with a PokeBall (25 left). | 210 EXP earned | Candies: 56 | lat: 42.357914 long: -71.064680 | Move1: PoisonStingFast Move2: Struggle | Rarity: VeryCommon | Capture Reason: Default | Shiny: No | Sex: Female
[01:22:57] (INFO) Saving 7 Sentret for evolve. Number of Sentret to be transferred: 0
[01:22:59] (INFO) Saving 70 Pidgey for evolve. Number of Pidgey to be transferred: 0
[01:23:01] (INFO) Saving 9 Marill for evolve. Number of Marill to be transferred: 0
[01:23:03] (INFO) Saving 5 Weedle for evolve. Number of Weedle to be transferred: 0
[01:23:05] (INFO) Saving 3 Ledyba for evolve. Number of Ledyba to be transferred: 0
[01:23:07] (INFO) Saving 5 Rattata for evolve. Number of Rattata to be transferred: 0
[01:23:09] (INFO) Saving 1 Shellder for evolve. Number of Shellder to be transferred: 0
[01:23:13] (INFO) Saving 2 Caterpie for evolve. Number of Caterpie to be transferred: 0
[01:23:16] (EVOLVED) Potential Evolutions: 106
[01:23:19] (UPDATE) Waiting to evolve 106 Pokemon once 81 more are caught! (159/240 for 99.6391627414334% inventory)

[01:23:24] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[01:23:30] (ERROR) Error: System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID, Boolean setDirty)
   at LiteDB.TransactionService.Save()
   at LiteDB.TransactionService.Complete(LiteTransaction trans)
   at LiteDB.LiteTransaction.Commit()
   at LiteDB.DbEngine.WriteTransaction[T](String colName, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteCollection`1.Delete(Query query)
   at PoGo.NecroBot.Logic.State.SessionStats.CleanOutExpiredStats() in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 198
   at PoGo.NecroBot.Logic.State.SessionStats.CatchThresholdExceeds(ISession session, Boolean printMessage) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 84
   at PoGo.NecroBot.Logic.Tasks.MSniperServiceTask.CheckSnipeConditions(ISession session) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\Tasks\MSniperServiceTask.cs:line 298
   at PoGo.NecroBot.Logic.Tasks.MSniperServiceTask.<Execute>d__42.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\Tasks\MSniperServiceTask.cs:line 786

**Comment by joe1chen** [comment]
Looks like an issue with LiteDB: https://github.com/mbdavid/LiteDB/issues/267

Will work on fixing this.

**Comment by TwoPointInfinity** [comment]
Ive been having this exact same issue. Please keep us updated.

**Comment by jjskuld** [comment]
This one is fixed now in the latest version.

**Comment by hardknoxni69a** [comment]
Issue Still Occuring With Latest Update To 3.0

**Comment by hardknoxni69a** [comment]
[10:03:08] (ERROR) Error: System.InvalidCastException: Unable to cast object of type 'LiteDB.DataPage' to type 'LiteDB.IndexPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc)
   at LiteDB.LiteEngine.<>c__DisplayClass61_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)
   at LiteDB.LiteCollection`1.Insert(T document)

**Comment by hardknoxni69a** [comment]
[10:11:15] (ERROR) Error: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiteDB.QueryGreater.<ExecuteIndex>d__3.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Enumerable.LongCount[TSource](IEnumerable`1 source)
   at LiteDB.LiteEngine.Count(String collection, Query query)
   at LiteDB.LiteCollection`1.Count(Query query)
   at PoGo.NecroBot.Logic.State.SessionStats.GetNumPokemonsInLast24Hours() in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 219
   at PoGo.NecroBot.Logic.State.SessionStats.CatchThresholdExceeds(ISession session, Boolean printMessage) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 86

**Comment by hardknoxni69a** [comment]
[08:48:52] (ERROR) Error: System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.TransactionService.Commit()
   at LiteDB.LiteEngine.Commit()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)
   at LiteDB.LiteCollection`1.Insert(T document)
   at PoGo.NecroBot.Logic.State.SessionStats.AddPokemonTimestamp(Int64 ts) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 190

**Comment by hardknoxni69a** [comment]
3 different errors from 3 different bots

**Comment by hardknoxni69a** [comment]
[10:16:27] (ERROR) Error: LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '58ee36b8d816b04390a7363b'.
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc)
   at LiteDB.LiteEngine.<>c__DisplayClass61_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)
   at LiteDB.LiteCollection`1.Insert(T document)
   at PoGo.NecroBot.Logic.State.SessionStats.AddPokestopTimestamp(Int64 ts) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 178

**Comment by jjskuld** [comment]
This is an issue related to #1516
