### ISSUE TITLE
api 0,57,4 min of api0,59,0

### ISSUE THREAD

**Issue by cocacolabanane** [Necrobot-Private/NecroBot#1429]
#[00:37:54] (ERROR) (KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.57.4, which is no longer supported.  Minimum API version is now 0.59.0.
[00:37:54] (ERROR) The bot will now exit after hitting the enter key.

Help pls thx

**Comment by eversonpiza** [comment]
Same here...

What can we do ?

**Comment by cocacolabanane** [comment]
Do you have the problem

**Comment by wmoser0** [comment]
I have the same problem as well glad i'm not the only one i thought i broke it haha.

**Comment by cocacolabanane** [comment]
What can we do now api code bought a week ago

**Comment by stfudonnie** [comment]
Anyone have a timeline for when necro is going to fix this?

**Comment by OnePunch87** [comment]
i've a a key bought unitill 24 april..
fix in few days please necrobot for new api call :(

**Comment by Furtif** [comment]
please wait update in cours...

**Comment by cocacolabanane** [comment]
Hello - = FurtiF ™ = -
Can we continue to use the code, or do we need to get new?
Reply with quote

**Comment by Furtif** [comment]
Wait a few times the new api 0.59.x is forced, consequently the bot is blocked, you have to correct the code and release a new build, this will be done as fast as possible.

**Comment by cocacolabanane** [comment]
ok thx

**Comment by OnePunch87** [comment]
we attend the new realease with the fix?or we must go in the config and put something of new in ??i hope for new release with all wark..is so fast for the persons with problems in "code config" :P

**Comment by Furtif** [comment]
Just wait or retrograde to v.1.0.0.148 and cancel the update

**Comment by OnePunch87** [comment]
is risk to use bot with old api  (when you come back to 148) ?
is more safety wait the new release with new fix api, right?

**Comment by Furtif** [comment]
148 and 147 uses 0.59.1 api not risk

**Comment by cocacolabanane** [comment]
THX man 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 07.04.17, 01:40, "--=FurtiF™=--" <notifications@github.com> schrieb:
Just wait or retrograde to v.1.0.0.148 and cancel the update

**Comment by OnePunch87** [comment]
omg...just new api O.O

April 6, 2017

Pokémon GO updated to version 0.61.0 for Android and 1.31.0 for iOS

Trainers,

Pokémon GO is in the process of being updated to version 0.61.0 for Android and 1.31.0 for iOS devices. Below are some release notes and comments from our development team.

Added Traditional Chinese language support.
Updated the Pokémon collection screen scroll bar.
Various bug fixes.
Minor text fixes.

but bot required 0.59..
the fix is for 0.61 for the new release?

**Comment by deadashot** [comment]
got this error too, they should fix it with the new version after 1.0.0.149

**Comment by OnePunch87** [comment]
i'm come back to 148..with 059 api call, attend a new release of bot (151?) with the features and the correct api 059 work ;)
i hope that the api 061 don't make problems in recent future, and next releases works correctly when will change api again.
thk for all work of the developer :)

**Comment by Monnie01** [comment]
Yeah thanks for all the work! Hope you can fix this again. Good luck!

**Comment by LEE-BC** [comment]
If you lose your partner's faith, you lose everything.
It's too much change.
What is the policy of Necrobot?

**Comment by OnePunch87** [comment]
i've this error with old version of necrobot
"[12:44:36] (ERRORE) Hashing Servers errors, throttling calls. SESSION INVALIDATED EXCEPTION"
how can i fix this? :)

**Comment by eversonpiza** [comment]
OnePunch87

This version has this problem.

Take a look here:
https://github.com/Necrobot-Private/NecroBot/issues/1411

**Comment by iSporean** [comment]
Which version is ok. Both 147 & 148 have same problems.

**Comment by OnePunch87** [comment]
146 is ok but use 057 maybe...
we haven't any bot that work coorectly for the moment, for problems of API or session invalid..

**Comment by iSporean** [comment]
146 is not ok.
(KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.57.4, which is no longer supported.  Minimum API version is now 0.59.0.

**Comment by iSporean** [comment]
Tried 145 to 149 none work succeswsfuly. 147 & 148 catch 2-3 pokemons and Hash error.

**Comment by cjhart** [comment]
I get this too, tried vs 148 works but with hash error.

Any ETA on a fix?

So addicted to the bot........ missing it......

Thanks for all the hard work devs.

**Comment by silvernova0** [comment]
Was working for me at 3pm central yesterday and stopped around 5 when I checked it again. Had put in a ticket about my api key not working expected it was the issue and they said my key was fine. Then noticed this and glad that I didn't just mess up mine.

**Comment by blackmamba0024** [comment]
ANY UPDATE HERE PLS?
I ONLY USE OTHER BOT..
BUT I NEED NECROBOT BECAUSE OF SNIPING..
PLS UPDATE FAST NECROBOT TEAM..

**Comment by ontano** [comment]
1.0.0.148 version 0.59.1 API works for me.
Just delete the option to update otherwise reset everything and rewrites the config.json no data.

**Comment by V1R4G3** [comment]
1.0.0.148 still experiencing Hashing Server Errors non-stop.

13:53:29] (ERROR) Hashing Servers errors, throttling calls. SESSION INVALIDATED EXCEPTION
[13:53:30] (ERROR) Resetting position before relogging in.

Then I get this:

[13:53:46] (INFO) PokemonGo.RocketAPI.Exceptions.SessionInvalidatedException: SESSION INVALIDATED EXCEPTION
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__9`7.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Download.<GetItemTemplates>d__5.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Download.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by eversonpiza** [comment]
jjskuld, 

thank you so much

**Comment by ontano** [comment]
1.0.0.148 version 0.59.1 API works for me.... today
Now 21.30  .... 0.61.0 API ... 
waiting for news

**Comment by silvernova0** [comment]
They updated to 151 and it works again for me

**Comment by silvernova0** [comment]
Just tried to run it again and stopped working, now it wants minimum version of .61 apk and stopped working as it is running .59.1

**Comment by mboeder** [comment]
Same here :-( kill switch stopped me a few minutes ago

Von meinem iPhone gesendet

Am 08.04.2017 um 21:56 schrieb silvernova0 <notifications@github.com<mailto:notifications@github.com>>:


Just tried to run it again and stopped working, now it wants minimum version of .61 apk and stopped working as it is running .59.1

**Comment by iSporean** [comment]
We need jjskuld to do his magic again quickly ;)

**Comment by silvernova0** [comment]
It is working again FYI but sniping is down for me, I didn't make any changes so have to see what is going on
