### ISSUE TITLE
Unhandled Exception: LiteDB.LiteException: Invalid database version: 6

### ISSUE THREAD

**Issue by cjhart** [Necrobot-Private/NecroBot#1443]
Getting this on the console app, 3 different accounts all do the same:

[08:11:24] () Configuration is up-to-date. Schema version: 23
[08:11:24] () Validating config.json...
[08:11:25] () Auth Configuration is up-to-date. Schema version: 23
[08:11:25] () Validating Auth.json...
[08:11:26] () Exception caught, writing LogBuffer.

Unhandled Exception: LiteDB.LiteException: Invalid database version: 6
   at LiteDB.HeaderPage.ReadContent(ByteReader reader)
   at LiteDB.BasePage.ReadPage(Byte[] buffer)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.EnsureIndex(String field, Boolean unique)
   at PoGo.NecroBot.Logic.State.SessionStats.InitializeDatabase(ISession session)
   at PoGo.NecroBot.Logic.State.SessionStats..ctor(ISession session)
   at PoGo.NecroBot.Logic.State.Session..ctor(GlobalSettings globalSettings, ISettings settings, ILogicSettings logicSettings, IElevationService elevationService, ITranslation translation)
   at PoGo.NecroBot.CLI.Program.RunBotWithParameters(Action`2 onBotStarted, String[] args)
   at PoGo.NecroBot.CLI.Program.Main(String[] args)

**Comment by jjskuld** [comment]
Yes dup. Just fixed in pull #1444

**Comment by jjskuld** [comment]
We'll fix this asap in v153

**Comment by cjhart** [comment]
Thanks Devs! :)
