### ISSUE TITLE
Gym Config

### ISSUE THREAD

**Issue by LimitedOC** [Necrobot-Private/NecroBot#1463]
Hey there

I would like some1 to share with me his Gym config that works. i did a setup on mine (5-10 version of necrobot ago) that is here on a topic (cant find it right now) and i was getting the bad request error when the bot was walked at enemy gyms. in the beggining it was goin normaly until the kick of enemy pokemons and then it was putting in the gym not that much powerfull pokemons of mine. for example i had dragonite that i wanted to put on the gym 3.3k CP and the bot used lapras 1.9k CP. i dont know how to set this up and also how to avoid the bad req error. i also see ppl that uses the bot and always are in gyms of my neighbour like 3.00 am that no1 is out of the house and they put like 3.0k CP. can some1 tell me what i have to do? (my config is the basic, the one that we have default when we download the bot) i use paid api. thanks and am sorry for my bad english

**Comment by hardknoxni69a** [comment]
Please join our discord server for basic questions as this is for issues. Gym is beta as well. Please take time to review your config properly as you may be missing the correct setting. But discord server is good place to get questions like that answered

**Comment by LimitedOC** [comment]
at the discord ppl are not answering, they just try to sell accounts from what i saw. now watch the error that i told you and ill post the config that i had

**Comment by LimitedOC** [comment]
[16:14:03] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[16:14:03] (ERROR) Error: System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST 
{"StatusCode":2,"RequestId":1458777931,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,55,54,49,48,48,48,55,49,56,54,55,51,51,51,17,129,229,94,202,99,251,66,64,25,196,160,227,218,130,161,55,64,33,38,197,199,39,100,251,66,64,41,198,223,246,4,137,161,55,64]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,218,148,176,146,182,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,50,97,99,51,102,57,53,102,56,97,98,97,101,49,102,97,102,57,100,52,55,53,52,100,57,52,102,100,56,51,53,49,55,55,57,50,97,49,55,57]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,97,53,52,97,49,98,50,57,53,97,52,51,57,100,52,51,49,101,102,48,49,100,50,56,102,56,56,55,52,51,51,50,49,52,56,54,100,55,54,52]},{"Type":6,"RequestMessage":[10,133,4,98,76,58,32,32,230,186,42,220,176,212,110,183,101,154,21,20,68,63,156,63,221,165,150,45,234,249,232,207,179,96,183,41,45,13,89,35,68,125,223,166,43,206,67,248,3,114,126,96,63,46,130,211,148,82,129,99,141,98,51,120,147,95,235,114,30,180,87,112,190,102,175,244,243,183,122,228,194,186,92,203,160,185,88,102,103,225,155,65,237,14,151,97,173,172,93,86,152,186,239,110,3,121,196,170,53,118,235,234,95,59,98,243,119,39,233,6,185,61,194,53,57,116,189,192,254,251,80,121,164,59,195,101,26,137,178,140,225,189,15,184,28,20,38,93,211,240,174,182,103,4,125,185,145,84,70,89,127,159,152,118,100,173,156,97,126,149,44,80,103,135,138,240,170,95,201,146,66,49,180,43,170,103,193,68,70,235,222,202,155,223,84,51,204,231,163,176,18,206,157,162,18,102,110,146,122,161,32,193,66,17,38,210,113,18,42,50,59,40,237,217,109,125,116,19,109,52,220,248,216,26,182,27,27,52,118,66,63,128,163,158,204,123,49,0,160,238,158,210,16,244,106,198,93,94,234,115,12,245,136,193,143,230,170,198,18,97,229,116,222,158,90,102,28,68,115,170,90,253,215,203,160,222,246,252,26,39,72,46,139,17,34,141,180,251,118,123,76,238,65,41,191,173,153,121,176,253,57,253,15,39,238,245,147,211,23,206,112,0,51,232,168,122,230,44,125,120,4,203,22,133,251,150,117,242,36,111,158,31,72,136,214,60,30,242,19,160,34,233,79,214,156,236,197,58,213,118,214,64,186,27,31,22,174,94,107,43,144,93,102,100,82,223,11,20,140,203,97,102,222,97,218,85,37,73,82,153,180,253,54,9,245,255,190,148,98,178,112,86,82,15,200,36,253,4,155,16,157,100,237,46,0,151,163,228,136,7,251,248,0,16,36,224,11,111,99,217,202,124,0,208,49,192,140,43,99,246,117,224,213,11,68,132,123,43,154,104,138,116,157,89,20,166,39,40,196,219,13,254,179,37,115,249,210,190,111,160,185,254,146,121,188,102,119,4,203,55,151,23,2,56,141,196,72,229,247,177,46,239,209,52,245,111,227,33,124,97,19,115,194,136,85,72,187,227,91,66,139,191,64,235,11,77,189,229,141,33]}],"Latitude":37.96398,"Longitude":23.6309,"Accuracy":65.0,"AuthInfo":null,"AuthTicket":{"Start":[153,63,104,113,153,219,227,228,193,23,244,248,201,245,98,238,92,18,186,156,103,220,25,243,206,212,132,125,51,158,252,248,21,222,205,68,173,49,4,179,79,195,215,252,96,41,0,196,93,210,98,22,76,48,98,227,221,0,10,125,166,161,138,230,237,74,66,81,227,234,74,150,81,10,20,229,100,111,204,249],"ExpireTimestampMs":1492004617372,"End":[100,250,41,127,142,161,99,91,164,222,153,167,248,35,103,166]},"MsSinceLastLocationfix":6666}
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:line 266
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PoGo.NecroBot.Logic.State.CachedGymGetails.LoadData(ISession session, FortData fort)
   at PoGo.NecroBot.Logic.State.CachedGymGetails..ctor(ISession session, FortData fort)
   at PoGo.NecroBot.Logic.State.GymTeamState.GetGymDetails(ISession session, FortData fort, Boolean force)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext()
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST 
{"StatusCode":2,"RequestId":1458777931,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,55,54,49,48,48,48,55,49,56,54,55,51,51,51,17,129,229,94,202,99,251,66,64,25,196,160,227,218,130,161,55,64,33,38,197,199,39,100,251,66,64,41,198,223,246,4,137,161,55,64]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,218,148,176,146,182,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,50,97,99,51,102,57,53,102,56,97,98,97,101,49,102,97,102,57,100,52,55,53,52,100,57,52,102,100,56,51,53,49,55,55,57,50,97,49,55,57]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,97,53,52,97,49,98,50,57,53,97,52,51,57,100,52,51,49,101,102,48,49,100,50,56,102,56,56,55,52,51,51,50,49,52,56,54,100,55,54,52]},{"Type":6,"RequestMessage":[10,133,4,98,76,58,32,32,230,186,42,220,176,212,110,183,101,154,21,20,68,63,156,63,221,165,150,45,234,249,232,207,179,96,183,41,45,13,89,35,68,125,223,166,43,206,67,248,3,114,126,96,63,46,130,211,148,82,129,99,141,98,51,120,147,95,235,114,30,180,87,112,190,102,175,244,243,183,122,228,194,186,92,203,160,185,88,102,103,225,155,65,237,14,151,97,173,172,93,86,152,186,239,110,3,121,196,170,53,118,235,234,95,59,98,243,119,39,233,6,185,61,194,53,57,116,189,192,254,251,80,121,164,59,195,101,26,137,178,140,225,189,15,184,28,20,38,93,211,240,174,182,103,4,125,185,145,84,70,89,127,159,152,118,100,173,156,97,126,149,44,80,103,135,138,240,170,95,201,146,66,49,180,43,170,103,193,68,70,235,222,202,155,223,84,51,204,231,163,176,18,206,157,162,18,102,110,146,122,161,32,193,66,17,38,210,113,18,42,50,59,40,237,217,109,125,116,19,109,52,220,248,216,26,182,27,27,52,118,66,63,128,163,158,204,123,49,0,160,238,158,210,16,244,106,198,93,94,234,115,12,245,136,193,143,230,170,198,18,97,229,116,222,158,90,102,28,68,115,170,90,253,215,203,160,222,246,252,26,39,72,46,139,17,34,141,180,251,118,123,76,238,65,41,191,173,153,121,176,253,57,253,15,39,238,245,147,211,23,206,112,0,51,232,168,122,230,44,125,120,4,203,22,133,251,150,117,242,36,111,158,31,72,136,214,60,30,242,19,160,34,233,79,214,156,236,197,58,213,118,214,64,186,27,31,22,174,94,107,43,144,93,102,100,82,223,11,20,140,203,97,102,222,97,218,85,37,73,82,153,180,253,54,9,245,255,190,148,98,178,112,86,82,15,200,36,253,4,155,16,157,100,237,46,0,151,163,228,136,7,251,248,0,16,36,224,11,111,99,217,202,124,0,208,49,192,140,43,99,246,117,224,213,11,68,132,123,43,154,104,138,116,157,89,20,166,39,40,196,219,13,254,179,37,115,249,210,190,111,160,185,254,146,121,188,102,119,4,203,55,151,23,2,56,141,196,72,229,247,177,46,239,209,52,245,111,227,33,124,97,19,115,194,136,85,72,187,227,91,66,139,191,64,235,11,77,189,229,141,33]}],"Latitude":37.96398,"Longitude":23.6309,"Accuracy":65.0,"AuthInfo":null,"AuthTicket":{"Start":[153,63,104,113,153,219,227,228,193,23,244,248,201,245,98,238,92,18,186,156,103,220,25,243,206,212,132,125,51,158,252,248,21,222,205,68,173,49,4,179,79,195,215,252,96,41,0,196,93,210,98,22,76,48,98,227,221,0,10,125,166,161,138,230,237,74,66,81,227,234,74,150,81,10,20,229,100,111,204,249],"ExpireTimestampMs":1492004617372,"End":[100,250,41,127,142,161,99,91,164,222,153,167,248,35,103,166]},"MsSinceLastLocationfix":6666}
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:line 266<---

**Comment by LimitedOC** [comment]
"Enable": true,
    "PrioritizeGymOverPokestop": false,
    "MaxDistance": 1000.0,
    "DefaultTeam": "Blue",
    "MaxCPToDeploy": 699,
    "MaxLevelToDeploy": 39,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 0,
    "CollectCoinAfterDeployed": 1,
    "EnableAttackGym": true,
    "MaxGymLevelToAttack": 10,
    "MaxDefendersToAttack": 10,
    "HealDefendersBeforeApplyToGym": true,
    "DontAttackAfterCoinsLimitReached": true,
    "EnableGymTraining": true,
    "TrainGymWhenMissingMaxPoints": 1,
    "MaxGymLvlToTrain": 9,
    "TrainAlreadyDefendedGym": true,
    "MinCpToUseInAttack": 15,
    "ButNotLessThanDefenderPercent": 0.4,
    "UsePokemonToAttackOnlyByCp": false,
    "ExcludeForGyms": [
      "kangaskhan",
      "tauros",
      "mrMime",
      "farfetchd"
    ],
    "DontUseDodge": false,
    "MinRevivePotions": 1,
    "PrioritizeGymWithFreeSlot": true,
    "SaveMaxRevives": true,
    "MaxTrainingRoundsOnOneGym": 5,

**Comment by LimitedOC** [comment]
so whats wrong with that? for others is working fine but for me it doesnt

**Comment by hardknoxni69a** [comment]
It's hard to tell u didn't send anything that happened before error

On Apr 12, 2017 9:18 AM, "LimitedOC" <notifications@github.com> wrote:

so whats wrong with that? for others is working fine but for me it doesnt

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Necrobot-Private/NecroBot/issues/1463#issuecomment-293572343>,
or mute the thread
