### ISSUE TITLE
Issue) SessionStats.db In Use Error

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#1516]
Receiving this error about every 10 minutes. I am positive there is only one instance open as this happens directly after a reboot so no way there is any process open that should be accessing it? Please help slightly annoying seeing red text all the time

[18:33:29] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[18:33:29] (ERROR) Error: System.IO.IOException: The process cannot access the file 'C:\Users\VAPORSS\OneDrive\Public\PokeCracks\AllBatches2\Batch4\VAPORSSMASTER31\config\VAPORSSMASTER71\SessionStats.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LiteDB.FileDiskService.Initialize(Logger log, String password)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.Count(Query query)
   at PoGo.NecroBot.Logic.State.SessionStats.GetNumPokemonsInLast24Hours() in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 219
   at PoGo.NecroBot.Logic.State.SessionStats.CatchThresholdExceeds(ISession session, Boolean printMessage) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 86
   at PoGo.NecroBot.Logic.Tasks.MSniperServiceTask.CheckSnipeConditions(ISession session) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\Tasks\MSniperServiceTask.cs:line 296
   at PoGo.NecroBot.Logic.Tasks.MSniperServiceTask.<Execute>d__42.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\Tasks\MSniperServiceTask.cs:line 784

**Comment by kobrezzzy** [comment]
having this same problem
