### ISSUE TITLE
Can anyone share their HASH KEY WITH MEE Please 

### ISSUE THREAD

**Issue by jaksh345** [Necrobot-Private/NecroBot#1548]
[00:35:02] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Your API Key: 1P6PXXXXXXXXXXXX5Q2E is incorrect or expired, please check auth.json (Pokefamer Message : Unauthorized)
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__13.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveN

**Comment by redking974** [comment]
Not the place to ask here, so please close it.

**Comment by Nackenschelle** [comment]
0D0Y1W6M2O5Z2I2N1X4M
