### ISSUE TITLE
Not able to connect to necrobot server expired hash key when it is not

### ISSUE THREAD

**Issue by azynstud** [Necrobot-Private/NecroBot#1556]
Hi, 

I am experiencing the following issue. I checked with bossland my key is fine, but displays the below:

11:15:13] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Your API Key: 8C5AXXXXXXXXXXXX4K5
[NecroBot2-2017-04-22-19-19-57.txt](https://github.com/Necrobot-Private/NecroBot/files/949906/NecroBot2-2017-04-22-19-19-57.txt)
A is incorrect or expired, please check auth.json (Pokefamer Message : Unauthorized)
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__13.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[11:15:33] (INFO) Logging in using Ptc pkmtrnr123
[11:15:34] (INFO) Connecting to ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket ....
[11:15:35] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Your API Key: 8C5AXXXXXXXXXXXX4K1A is incorrect or expired, please check auth.json (Pokefamer Message : Unauthorized)
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__13.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[11:15:50] (ATTENTION) Couldn't establish the connection to necrobot socket server : ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket

**Comment by OrdsonX** [comment]
You probably using Pokefarmer key instead of pogodev key.

**Comment by azynstud** [comment]
This is the key that i used before and this is a hashkey for pogodev. It worked before, but recently stopped.


________________________________

**Comment by Tim22008** [comment]
same Problem
did u find a solutuin?

**Comment by azynstud** [comment]
No did you?

Sent from my iPhone

On Apr 23, 2017, at 1:37 PM, Tim22008 <notifications@github.com<mailto:notifications@github.com>> wrote:


same Problem
did u find a solutuin?

**Comment by azynstud** [comment]
I hope we can figure out a way to fix this. Do you think it's the key? Should we buy another key? I also checked with boss land my key is fine.

Sent from my iPhone

On Apr 23, 2017, at 1:37 PM, Tim22008 <notifications@github.com<mailto:notifications@github.com>> wrote:


same Problem
did u find a solutuin?

**Comment by Buckrogers81** [comment]
I had the same Problem. I downloadet the latest Version of the Bot into a new Folder startet it and it workt...

**Comment by azynstud** [comment]
I think I solved my own problem. I just had the wrong key in the pogo dev. I used the prefilled key that was already prefilled instead of deleting that one and typing in the key I bought from bossland. ugh how dumb of me.

**Comment by redking974** [comment]
Yes, your log shows that was the prefilled key (revoked). Could you close the issue please ?
And be careful, your log contains your nickname.
