### ISSUE TITLE
Can't Launch

### ISSUE THREAD

**Issue by galacticfat** [Necrobot-Private/NecroBot#1593]
### Expected Behavior:

First time startup prompt to open / auth or config .json files to be made

### Actual Behavior:

Crash and no new files in the folder 'Config'

### Your config.json:
There is no .json because nothing was generated when I opened the exec

### (OPTIONAL) Your Log:
```
[23:20:58] () Exception caught, writing LogBuffer.

```

### Detailed Steps to Reproduce:

I freshly downloaded <a href = 'https://github.com/Necrobot-Private/NecroBot/releases/download/v1.0.0.159/NecroBot2.Console.1.0.0.159.zip'> NecroBot2.Console.1.0.0.159.zip</a> off the Git page.

I extracted it into a folder onto my desktop, "t".

I try to execute the program 'NecroBot2' and the program crashes (there was nothing in config at the time other than translations)

![image](https://cloud.githubusercontent.com/assets/28210968/25561187/ced31752-2d33-11e7-97c3-5535671f4da7.png)

I look into configs again, still nothing

![image](https://cloud.githubusercontent.com/assets/28210968/25561181/bd35e27c-2d33-11e7-9d55-021188e2e568.png)

### Other Information
(Attach zip files if needed.)

Version: 1.0.0.159
Windows Version: 8
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Launch

**Comment by Furtif** [comment]
Please install the dependencies https://www.microsoft.com/en-us/download/details.aspx?id=53321

**Comment by galacticfat** [comment]
[13:03:47] () Configuration is up-to-date. Schema version: 16
[13:03:47] () Validating config.json...
[13:03:47] () Auth Configuration is up-to-date. Schema version: 16
[13:03:47] () Validating auth.json...
[13:03:48] () You bot will start after 15 second, You are running bot with  Legacy API (0.45) it will increase your risk to be banned and trigger captcha. Config captcha in config.json to auto resolve them
[13:03:48] (INFO) Websocket listening on at  wss://localhost:14251 or ws://localhost:14252 
[13:03:48] (INFO) jaysenmickeu@gmail.com(Level: ??)			Runtime : 00:00:00:00
[13:03:48] (INFO) Your IP is: 67.247.55.85
[13:03:49] (INFO) https://github.com/Necrobot-Private/NecroBot/releases/download/v1.0.0.160/NecroBot2.Win.zip
[13:03:49] (UPDATE) Downloading and apply Update...
[13:03:49] (INFO) C:\Users\Jason\Desktop\newb\NecroBot2.Win.zip
[13:03:49] (UPDATE) Finished downloading newest Release...
[13:03:49] (INFO) Logging in using Google jaysenmickeu@gmail.com
[13:03:52] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__4`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\LoginState.cs:line 50

Still doesn't work : //

**Comment by galacticfat** [comment]
[13:03:47] () Configuration is up-to-date. Schema version: 16
[13:03:47] () Validating config.json...
[13:03:47] () Auth Configuration is up-to-date. Schema version: 16
[13:03:47] () Validating auth.json...
[13:03:48] () You bot will start after 15 second, You are running bot with  Legacy API (0.45) it will increase your risk to be banned and trigger captcha. Config captcha in config.json to auto resolve them
[13:03:48] (INFO) Websocket listening on at  wss://localhost:14251 or ws://localhost:14252 
[13:03:48] (INFO) jaysenmickeu@gmail.com(Level: ??)			Runtime : 00:00:00:00
[13:03:48] (INFO) Your IP is: xx.xxx.xx.xx 
[13:03:49] (INFO) https://github.com/Necrobot-Private/NecroBot/releases/download/v1.0.0.160/NecroBot2.Win.zip
[13:03:49] (UPDATE) Downloading and apply Update...
[13:03:49] (INFO) C:\Users\Jason\Desktop\newb\NecroBot2.Win.zip
[13:03:49] (UPDATE) Finished downloading newest Release...
[13:03:49] (INFO) Logging in using Google jaysenmickeu@gmail.com
[13:03:52] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__4`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\LoginState.cs:line 50

**Comment by informer0827** [comment]
you should buy an API key instead using old 0.45 free API

**Comment by Lord-Haji** [comment]
RocketAPI doesn't work
