### ISSUE TITLE
Console errors in win gui

### ISSUE THREAD

**Issue by jjskuld** [Necrobot-Private/NecroBot#1708]
### Actual Behavior:
After removal of console, we are seeing these kinds of errors:

```
[16:41:07] (ATTENTION) Detected realistic Traveling , using Default Settings inside config.json
[16:41:07] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7845040259027 Lng: -73.969877987857
[16:41:07] (ATTENTION) Program will continue after the key press...
[16:41:07] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[16:41:07] (ERROR) Error: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at PoGo.NecroBot.Logic.State.LoadSaveState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext()
[16:41:07] (INFO) Logging in using Ptc GjNrqSNG
[16:41:25] (INFO) Playing as XZovs4Psfj
```

For now we can restore the console functionality until we remove all references to the console.

**Comment by CDAGaming** [comment]
Fix for this is just adding ConsoleHelper.AllocConsole() again. Unfortunatley, i dont see any way to FULLY remove all references to it but it can be minimalized
