### ISSUE TITLE
Bot crashes right after PTC login

### ISSUE THREAD

**Issue by amourification** [Necrobot-Private/NecroBot#1718]
Hello,

Seems like I can't use Necrobot with my PTC account! I have created a fresh PTC account for testing purposes and the account worked well at first and the bot was able to choose avatar gender and set nickname and catch the starter pokemon and even perform rename according to IV, but then the bot signed out and kept giving me this error each time I try to log in.

I tried the account on my iPhone and the game loaded successfully and I was able to play so, not banned.

What caused this? and how to resolve the issue?

[10:56:56] (UPDATE) Perfect! You already have the newest Version 1.0.0.172
[10:56:56] (INFO) Your IP is: **********
[10:56:56] (INFO) Logging in using Ptc accountname
[10:57:22] (INFO) Playing as accountname
[10:57:23] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7852248979849 Lng: -73.9683557899023
[10:57:27] (INFO) ====== DisplayHighestsCP ======
[10:57:27] (INFO) # CP   10/ 831 | (66.67% perfect)     | Lvl 01         NAME: Charmander        MOVE1: ScratchFast          MOVE2: Flamethrower         Candy: 3
[10:57:27] (INFO) ====== DisplayHighestsPerfect ======
[10:57:27] (INFO) # CP   10/ 831 | (66.67% perfect)     | Lvl 01         NAME: Charmander        MOVE1: ScratchFast          MOVE2: Flamethrower         Candy: 3
[10:57:27] (INFO) Amount of Pokemon Seen: 1/231, Amount of Pokemon Caught: 1/231
[10:57:27] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[10:57:27] (ERROR) Error: LiteDB.LiteException: Invalid database version: 6
   at LiteDB.HeaderPage.ReadContent(ByteReader reader)
   at LiteDB.BasePage.ReadPage(Byte[] buffer)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at PoGo.NecroBot.Logic.State.SessionStats.LoadLegacyData(ISession session)
   at PoGo.NecroBot.Logic.State.SessionStats.CleanOutExpiredStats()
   at PoGo.NecroBot.Logic.State.SessionStats.CatchThresholdExceeds(ISession session, Boolean printMessage)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext()

**Comment by amourification** [comment]
Okay, deleting my accounts.db seemed to fix the problem and everything works great now.
