### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wilsondgonzales** [Necrobot-Private/NecroBot#173]
```
[11:57:06] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<>c__DisplayClass23_0.<GetHighestPokemonOfTypeByIv>b__0(PokemonData x) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 270
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestPokemonOfTypeByIv>d__23.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 270
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.LevelUpPokemonTask.<UpgradeSinglePokemon>d__2.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\LevelUpPokemonTask.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\LevelUpPokemonTask.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.HumanRandomActionTask.<Execute>d__1.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanRandomActionTask.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63
```

"PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 5000,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 928,
    "CatchPokemonLimitMinutes": 1470,
    "UseIncenseConstantly": true,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 70,
    "UseLuckyEggsWhileEvolving": true,
    "UseBerriesMinCp": 2000,
    "UseBerriesMinIv": 95.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 10,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{0}",
    "FavoriteMinIvPercentage": 100.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 10,
    "UseGreatBallAboveCp": 2100,
    "UseUltraBallAboveCp": 2600,
    "UseMasterBallAboveCp": 3000,
    "UseGreatBallAboveIv": 95.0,
    "UseUltraBallAboveIv": 98.0,
    "UseGreatBallBelowCatchProbability": 0.1,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.03,
    "AutomaticallyLevelUpPokemon": true,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 50,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 100.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 70.0,
    "KeepPokemonsThatCanEvolve": true,
    "KeepMinCp": 2400,
    "KeepMinIvPercentage": 98.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false

Version: 9.9.5
Windows Version: win7

**Comment by Silph-Road** [comment]
Did the error go away or what ?
Is this a repeatable issue?

**Comment by Silph-Road** [comment]
Also update to latest and then try again and post back results if you find an issue.
