### ISSUE TITLE
Update 1.0.0.178 makes NecroBot crash

### ISSUE THREAD

**Issue by Misc4HD** [Necrobot-Private/NecroBot#1820]
After updating I got this error, even tried a fresh install but i still got this error.

[16:46:03] (INFO) Exception caught, writing LogBuffer.

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PoGo.Necrobot.Window.MainClientWindow.<>c__DisplayClass20_0.<LogToConsoleTab>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at PoGo.Necrobot.Window.App.Main()

Version: 1.0.0.178
Windows Version: 10 Pro
What is affected: startup

**Comment by Kviller** [comment]
Same error on Win7 SP1

**Comment by frkwhiteangel** [comment]
#1823 same here.

**Comment by zmud** [comment]
Same error upon startup
deleted config files and put in info again
crashed again upon completion
V: 1.0.0.178
Window 10 64 bit

**Comment by Jean-Daniel** [comment]
The ConsoleColors dictionary does not contains entry for LogLevel.BotStats so trying to log using that level crash the app.

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/1825

**Comment by TheWizard1328** [comment]
This error hat been fixed as of yesterday.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
