### ISSUE TITLE
Error for accounts that have participated in raids 

### ISSUE THREAD

**Issue by masrudyn** [Necrobot-Private/NecroBot#1843]
Accounts that have participated in raids will have this error when starting necrobot:
[13:51:14] (INFO) System.Exception: Unexpected inventory error. Could not generate hash code. at PokemonGo.RocketAPI.Rpc.Inventory.GetInventoryItemHashKey(InventoryItem item) at PokemonGo.RocketAPI.Rpc.Inventory.AddRemoveOrUpdateItem(InventoryItem item) at PokemonGo.RocketAPI.Rpc.Inventory.MergeWith(GetInventoryResponse update) at PokemonGo.RocketAPI.Helpers.CommonRequest.ProcessGetInventoryResponse(Client client, GetInventoryResponse getInventoryResponse) at PokemonGo.RocketAPI.Rpc.Download.<GetRemoteConfigVersion>d6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d10.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by masrudyn** [comment]
Sorry, this issue is same as #1840
