### ISSUE TITLE
could not generate hash code 

### ISSUE THREAD

**Issue by Adey123456789** [Necrobot-Private/NecroBot#1847]
[19:50:30] (INFO) Logging in using Ptc adey1984
[19:50:48] (INFO) System.Exception: Unexpected inventory error. Could not generate hash code.
   at PokemonGo.RocketAPI.Rpc.Inventory.GetInventoryItemHashKey(InventoryItem item)
   at PokemonGo.RocketAPI.Rpc.Inventory.AddRemoveOrUpdateItem(InventoryItem item)
   at PokemonGo.RocketAPI.Rpc.Inventory.MergeWith(GetInventoryResponse update)
   at PokemonGo.RocketAPI.Helpers.CommonRequest.ProcessGetInventoryResponse(Client client, GetInventoryResponse getInventoryResponse)
   at PokemonGo.RocketAPI.Rpc.Download.<GetRemoteConfigVersion>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by tevski** [comment]
i am having the same prob at PokemonGo.RocketAPI.Rpc.Inventory.GetInventoryItemHashKey(InventoryItem item)
   at PokemonGo.RocketAPI.Rpc.Inventory.AddRemoveOrUpdateItem(InventoryItem item)
   at PokemonGo.RocketAPI.Rpc.Inventory.MergeWith(GetInventoryResponse update)
   at PokemonGo.RocketAPI.Helpers.CommonRequest.ProcessGetInventoryResponse(Client client, GetInventoryResponse getInventoryResponse)
   at PokemonGo.RocketAPI.Rpc.Download.<GetRemoteConfigVersion>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by Furtif** [comment]
wait for next relesase
