### ISSUE TITLE
Bot starting with error [Fresh installation of 0.9.9.6]

### ISSUE THREAD

**Issue by popsoda27** [Necrobot-Private/NecroBot#188]
### Expected Behavior:
Bot loggin in and running as per normal

### Actual Behavior:
Throwing error right after login

### Your config.json:
```
All parts of config at default except starting location of course

```

### (OPTIONAL) Your Log:
```
[21:25:07] Logging in using Google
[21:25:33] System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Cryptography.X509Certificates, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Security.Cryptography.X509Certificates, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Cryptography.X509Certificates, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Security.Cryptography.X509Certificates, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\Acer\Desktop\New folder (2)\Open Source Bot\Necrobot-private\NecroBot-master\FeroxRev\Helpers\RetryHandler.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\Acer\Desktop\New folder (2)\Open Source Bot\Necrobot-private\NecroBot-master\FeroxRev\Helpers\RetryHandler.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\Acer\Desktop\New folder (2)\Open Source Bot\Necrobot-private\NecroBot-master\FeroxRev\Extensions\HttpClientExtensions.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__10`1.MoveNext() in C:\Users\Acer\Desktop\New folder (2)\Open Source Bot\Necrobot-private\NecroBot-master\FeroxRev\Rpc\BaseRpc.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<FireRequestBlock>d__4.MoveNext() in C:\Users\Acer\Desktop\New folder (2)\Open Source Bot\Necrobot-private\NecroBot-master\FeroxRev\Rpc\Login.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Acer\Desktop\New folder (2)\Open Source Bot\Necrobot-private\NecroBot-master\FeroxRev\Rpc\Login.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Acer\Desktop\New folder (2)\Open Source Bot\Necrobot-private\NecroBot-master\PoGo.NecroBot.Logic\State\LoginState.cs:line 35

```

### Detailed Steps to Reproduce:
Starting bot

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by BoydTM** [comment]
repeated ... delete NecroBot2.exe.config

**Comment by ajns73** [comment]
Duplicate here #184
