### ISSUE TITLE
Problem using legacy api

### ISSUE THREAD

**Issue by BrightStraightReality** [Necrobot-Private/NecroBot#1881]
I am currently trying to use the legacy api (yes I understand the risks) and keep getting this error

[17:57:41] () You bot will start after 15 seconds, You are running bot with Legacy API (0.45), but it will increase your risk of being banned and triggering captchas. Config Captchas in config.json to auto-resolve them
[17:57:41] () Exception caught, writing LogBuffer.

Unhandled Exception: PokemonGo.RocketAPI.Exceptions.AuthConfigException: No API method was selected in auth.json
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings)
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings)
   at PoGo.NecroBot.Logic.State.Session..ctor(GlobalSettings globalSettings, ISettings settings, ILogicSettings logicSettings, IElevationService elevationService, ITranslation translation)
   at PoGo.NecroBot.CLI.Program.RunBotWithParameters(Action`2 onBotStarted, String[] args)
   at PoGo.NecroBot.CLI.Program.Main(String[] args)

my auth.json file looks like this

 "APIConfig": {
    "UsePogoDevAPI": false,
    "AuthAPIKey": "0.45",
    "UseLegacyAPI": true,
    "DiplayHashServerLog": true
  }

Any advice? I know I'm not putting the wright info in the AuthAPIKey line but I dont know what I should be putting there.

Cheers

**Comment by macinmn** [comment]
search "legacy" in all issues (including closed) and you will see your answer many many times

**Comment by BrightStraightReality** [comment]
Cheers mate

**Comment by Furtif** [comment]
Legacy not works
