### ISSUE TITLE
Error PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext()

### ISSUE THREAD

**Issue by masrudyn** [Necrobot-Private/NecroBot#1905]
I keep getting this error on 2 of my accounts (using other accounts with the same config does not produce the error below):
[01:45:00] (INFO) System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[01:45:20] (INFO) Logging in using Ptc inzaniti
[01:45:24] (INFO) System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/NecroBot#requirements net 4.6.2 or 4.7

**Comment by masrudyn** [comment]
I've already got 4.7 installed.

Actually this error is account specific. 

I am running multiple bots (using different proxy IPs). Only 1 account gets this error. The rest are working fine. I've tried using the same config as those accounts that are working but I still get this error.

**Comment by Sdwz** [comment]
Same is happening here for 2 of my account

**Comment by masrudyn** [comment]
I am using .NET 4.7.02053 too

**Comment by hurob** [comment]
Same is happening to my only account. I am using 4.7.02046
