### ISSUE TITLE
new problem...dunno what is this

### ISSUE THREAD

**Issue by siangs** [Necrobot-Private/NecroBot#192]
01:42:24] Traveling to Pokestop/Gym:  (10m) (0 seconds) (route NecroBot Walk)
[01:42:26] Looking for Pokemon...
[01:42:26] Looking for incense Pokemon...
[01:42:27] Looking for Pokemon...
[01:42:28] Looking for incense Pokemon...
[01:42:28] Looking for lure Pokemon...
[01:42:29] Pokemon Servers might be offline / unstable. Trying again...
[01:42:30] Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'POGOProtos.Networking.Responses.DiskEncounterResponse' does not contain a definition for 'WildPokemon'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__9.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<DoActionAtPokeStop>d__18.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63

**Comment by BoydTM** [comment]
already reported (https://github.com/Necrobot-Private/NecroBot/issues/179), if you wish to use that version - just move outside the area with pokestops + lures

**Comment by CreativiTimothy** [comment]
Same issue, not sure what's going on
