### ISSUE TITLE
Issue on new computer

### ISSUE THREAD

**Issue by Joshuam08** [Necrobot-Private/NecroBot#1920]
Hi all,
I just setup a new server to run Necrobot and transferred my necrobot files including config to a new PC but when I run it, it goes through the first few stages but then gets stuck at logging into google account and then outputs below.

[09:07:21] (UPDATE) Perfect! You already have the newest Version 1.0.0.185
[09:07:21] (INFO) Logging in using Google XXX@gmail.com
[09:08:39] (INFO) PokemonGo.RocketAPI.Exceptions.TokenRefreshException: Error refreshing access token.
   at PokemonGo.RocketAPI.Rpc.Login.<Reauthenticate>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<GetValidAccessToken>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

Any idea about this one?

**Comment by Lord-Haji** [comment]
.Net 4.6.2

**Comment by Joshuam08** [comment]
I thought it was a .net issue but I installed net 4.7. Thanks mate.
