### ISSUE TITLE
[19:53:13] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (https://pokehash.buddyauth.com/api/v137_1/hash) might down!

### ISSUE THREAD

**Issue by dimitris63** [Necrobot-Private/NecroBot#1946]
I am getting the below error message. Why am I getting the error message

[19:53:13] (INFO) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (https://pokehash.buddyauth.com/api/v137_1/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefarmerHasher.<RequestHashesAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by blackuGT** [comment]
When this error pops up?

**Comment by dimitris63** [comment]
@Lord-Haji why was this closed. why is the message being generated?
@blackuGT this error message was generated on 7/29 and it repeated every 5min

**Comment by blackuGT** [comment]
@dimitris63 This is just API hash error, nothing special.
