### ISSUE TITLE
need help , how can i solve this issue?

### ISSUE THREAD

**Issue by elvis000502** [Necrobot-Private/NecroBot#207]
keep showing this error once i updated to v0.9.9.7

### (OPTIONAL) Your Log:

[01:49:44] Pokemon Servers might be offline / unstable. Trying again...
[01:49:45] Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'POGOProtos.Networking.Responses.DiskEncounterResponse' does not contain a definition for 'WildPokemon'
   at CallSite.Target(Closure , CallSite , Object )
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__9.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<DoActionAtPokeStop>d__18.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63

```




Version: 0.9.9.7
Windows Version: window 8.1
What is affected (other): 
attachment is my config, hopefully anyone can help me
[config.zip](https://github.com/Necrobot-Private/NecroBot/files/478875/config.zip)

**Comment by BoydTM** [comment]
move back to 0.9.9.4 until stable version is released ...

**Comment by elvis000502** [comment]
i try it now thx bro
