### ISSUE TITLE
Necrobot 0.8.8 cannot use right now, what's happen?

### ISSUE THREAD

**Issue by henbae** [Necrobot-Private/NecroBot#236]
why i cannot login ?

[00:21:23] System.BadImageFormatException: Could not load file or assembly 'file:///Z:\share\Release0.8.8\86araTM4z9VzLMZZ.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'file:///Z:\share\Release0.8.8\86araTM4z9VzLMZZ.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at NecroBot_Network_Logic.Encryption.Encrypt(Byte[] input, Byte[] iv)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(IEnumerable`1 requests)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(Request[] customRequests)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(RequestType type, IMessage message)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by ajns73** [comment]
@henbae This topic has been covered repeatedly. 0.8.8 has elements of 2 different APIs in it. One of those APIs (.33) has been phased out by Niantic and will probably not work. Continuing to use outdated bots greatly increases your chances of being banned and, through your behavior, giving Niantic a blue print for banning other accounts showing similar tendencies, PLEASE update to 0.9.9.9 and try to keep your bot updated (at least to version 0.9.9.5)

**Comment by petpetpetvm** [comment]
0.9.9.5 updated up to 0.35 api, 0.8.8 uses 0.33 which is forced update by niantic, you should keep checking issues page, there was a topic that said about this :)

**Comment by ajns73** [comment]
This is probably like pounding sand but, oh well: There is a "Closed" issues section as well as "Open." Both can be searched BEFORE an issue is posted. If you really feel your issue is substantially different than a previous one on the same topic, post it. If not don't, or mark it as something else, or take it to discord to discuss.
