### ISSUE TITLE
Human Walk Snipe + GPX = Bot Crashes and gets Exception:       Error: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by DragonBlazer** [Necrobot-Private/NecroBot#251]
### Expected Behavior:
Bot works normally.

### Actual Behavior:
Bot will crash when it hits this error:
"[15:54:13] (SNIPER) (HUMAN WALK) destination reached | lat:......."
**"[15:54:22] (ERROR) Pokemon Servers might be offline / unstable. Trying again..."**

### Your config.json:
```
  "GPXConfig": {
    "UseGpxPathing": true,
    "GpxFile": "GPXPath.GPX"

&

  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 5000.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 5000.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": false,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UsePokecrew": true,
    "UsePokesnipers": true,
    "UsePokeZZ": true,
    "UsePokeWatcher": true,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": true


```

### (OPTIONAL) Your Log:
```
[15:54:13] (SNIPER) (HUMAN WALK) destination reached | lat: 41.8078124418922, lng: -97.428542404839 | wait :10.00 sec
[15:54:22] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[15:54:23] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<WalkingBackGPXPath>d__14.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<Execute>d__13.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<>c__DisplayClass3_0.<<Execute>b__0>d.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.HumanPathWalkingStrategy.<Walk>d__4.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\HumanPathWalkingStrategy.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__13.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63
[15:54:23] (INFO) Logging in using Ptc
```

### Detailed Steps to Reproduce:

- Use Default Config with settings pasted above. 
<br>
The crash will happen when this error happens:
**"[15:54:22] (ERROR) Pokemon Servers might be offline / unstable. Trying again..."**

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): GPX, Snipe, Catch, Human Walk Snipe.

**Comment by DragonBlazer** [comment]
This happens like every 10 minutes btw

**Comment by jjskuld** [comment]
@DragonBlazer Making a new release... stay tuned.

**Comment by DragonBlazer** [comment]
Cool thanks! 
Too many multiple logins and crashes and logins and crashes again and again.

**Comment by jjskuld** [comment]
See if https://github.com/Necrobot-Private/NecroBot/releases/tag/v1.0.0.3 fixes.

**Comment by DragonBlazer** [comment]
Testing, will post back with results.

**Comment by DragonBlazer** [comment]
Tested for a couple hours and its fixed. Thanks.
