### ISSUE TITLE
Exception after ptc token expiration and Nyantic servers unstable

### ISSUE THREAD

**Issue by shymi** [Necrobot-Private/NecroBot#326]
Happened to me today and didn't find bug about this. Copy of the full stack trace(after the last login the highes CP/IV lists(only with 2 entries each - is it suppose to be only 2) are shown):

```
[13:04:18] (ERROR) PTC Login Token expired. Relogging...
[13:04:18] (INFO) Trying again in 1 seconds...
[13:04:26] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[13:04:27] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<RefreshCachedInventory>d__45.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 612
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetCachedInventory>d__16.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<DeletePokemonFromInvById>d__14.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.HumanRandomActionTask.<TransferRandom>d__2.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanRandomActionTask.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__9.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 439
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<OnWalkingToPokeStopOrGym>d__15.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass14_0.<<WalkingToPokeStop>b__0>d.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.BaseWalkStrategy.<DoWalk>d__18.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\BaseWalkStrategy.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__4.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__13.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__14.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63
[13:04:27] (INFO) Logging in using Ptc
[13:04:31] (INFO) Playing as ********
[13:04:31] (ATTENTION) Detected realistic Traveling , using Default Settings inside config.json
[13:04:31] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 42.6844572335371 Lng: 23.3235310641898
[13:04:31] (ATTENTION) Without a Google Api, you will have 2500 free quota limit, if you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key
[13:04:55] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[13:04:56] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__38.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 438
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__24.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 295
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63
[13:04:56] (INFO) Logging in using Ptc
[13:05:00] (INFO) Playing as *************
[13:05:00] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 42.6844572335371 Lng: 23.3235310641898
[13:05:00] (ATTENTION) Without a Google Api, you will have 2500 free quota limit, if you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key
[13:05:25] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[13:05:26] (ERROR) Error: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.PoGoUtils.PokemonInfo.GetCandy(PokemonData pokemon, List`1 PokemonFamilies, IEnumerable`1 PokemonSettings) in c:\projects\necrobot2\PoGo.NecroBot.Logic\PoGoUtils\PokemonInfo.cs:line 592
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<>c__DisplayClass2_0.<Execute>b__0(PokemonData pokemon) in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 35
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63
[13:05:26] (INFO) Logging in using Ptc
[13:05:29] (INFO) Playing as *************
```

P.S. Necrobot is on my desktop - I don't know why there's c:\projects\necrobot2\ directory mentioned in stacktrace.
P.P.S. Just now the token needed to be refreshed again and the error didn't happen, so I think the problem might be with the throttling the api calls functionality.

**Comment by shymi** [comment]
Additional info:
When I downloaded the client(v 1.0.0.15 that was updated itself to latest) I had changed the "" values in the auth.json(in the DeviceConfig object, can't remember which were exactly), that caused errors to be thrown, to null.

**Comment by gjimenezf** [comment]
I have the same issue

**Comment by AmyEscano** [comment]
#310 - they are already working on it

dont post your device info, you might get banned
