### ISSUE TITLE
PokemonGo.RocketAPI.Exceptions.InvalidResponseException

### ISSUE THREAD

**Issue by cspooner1999** [Necrobot-Private/NecroBot#478]
windows 10 version while starting I get the following:
PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
can anyone help?

**Comment by cspooner1999** [comment]
I have tried deleting and starting over to no avail.

**Comment by BlaayLoock** [comment]
cspooner1999, Just edit auth.json 
`  "APIConfig": {
    "UsePogoDevAPI": false,
    "AuthAPIKey": null,
    "UseLegacyAPI": true
  },`
(Necrobot also support legacy api - 0.45. use it at your own risk (this is free ))
 and try again

P.S. There was an error with authorization, bought another Pogodev API key. Working key is defined as poor. Established "UsePogoDevAPI": false, and it worked with no errors.

**Comment by cspooner1999** [comment]
sorry I am noobish, I bought a key does that mean my key is broken? I would not like to use this with legacy.

**Comment by samuraitruong** [comment]
do you still having that issue?

**Comment by cspooner1999** [comment]
trying now sorry I got distracted. give me a few minutes and I will reply.

**Comment by cspooner1999** [comment]
yes still having the same issue. I have not tried setting the bot to legacy api because I do not want to use that for safety reasons. I just bought that code yesterday it should not be bad.

**Comment by cspooner1999** [comment]
Ok for giggles I tried changing to the legacy with a burner account and got the following:
[08:47:37] (INFO) Logging in using Google
[08:47:41] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__2.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\LoginState.cs:line 43

**Comment by cspooner1999** [comment]
ok so I may know what is going on. I think that I bought the key using a different email. The email states that it is linked to my email. BUT, the email that I am using to login to pokemon go is different than the linked email. Is this an issue? if so, how would I go about changing that?

**Comment by cspooner1999** [comment]
Ok so I switched to the account linked to the key and tried with the same error message. Can someone help?

**Comment by cspooner1999** [comment]
The email address does not matter according to pokehash. Seems I am having issues with the program.

**Comment by BlaayLoock** [comment]
cspooner1999, I am sure that your key is valid You may want to remove the "Cache" folder, "temp" directory% NecroBot%. Install an earlier version of the robot, such as 0.47, 0.48.  Experiment  :)

Change the IP address of the connection (switch to turn off MDRG / 4G, for example) to avoid the temporary "softban on IP" Finally, the patience, the server Niantiс can also have problems 

I read the news on POGODEV , all the keys will be good to work in their quota. Will 100% stably Niantis server ? I do not know it

**Comment by samuraitruong** [comment]
seem weird to me, are you able to login normally on phone

**Comment by cspooner1999** [comment]
Ok so it seems it works on my windows 7 computer but not my windows 10 computer. Thanks for the help.

**Comment by cspooner1999** [comment]
yes I am able to log in on my phone.

**Comment by samuraitruong** [comment]
I use windows 10 and it work fine. think it only related to special OS and machine, I will leave it open until know why it happen to you

**Comment by hardknoxni69a** [comment]
i take it the latest versions have resolved your problem let us know if we need to reopen issue
