### ISSUE TITLE
Stuck after captcha

### ISSUE THREAD

**Issue by boscorelly** [Necrobot-Private/NecroBot#486]
Hi,

work not working after captcha.
Last ligne is (SERVICE) (Identity) [ xxxx ] connection established

**Comment by samuraitruong** [comment]
you should turn off MSniperService

**Comment by boscorelly** [comment]
not working...

**Comment by johnnylim78** [comment]
after the delay to do the captcha and i cannot use the bot the message show anyone can help me

Unhandled Exception: PokemonGo.RocketAPI.Exceptions.CaptchaException: Exception of type 'PokemonGo.RocketAPI.Exceptions.CaptchaException' was thrown.
   at PoGo.NecroBot.Logic.Inventory.<GetPlayerData>d__29.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 380
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Starting ChromeDriver 2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30) on port 49166
Only local connections are allowed.

**Comment by boscorelly** [comment]
it may be because there was no answer to the captcha

**Comment by johnnylim78** [comment]
Yes I no answer
