### ISSUE TITLE
Bad Request Error

### ISSUE THREAD

**Issue by SavantLynx** [Necrobot-Private/NecroBot#491]
[18:36:13] (ATTENTION) Bulk transfer 100 pokemons was failed...
[18:36:14] (ERROR) Bad Request - If you see this message please conpy error log & screenshot send back to dev asap.
[18:36:14] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":3305596767340331021,"Requests":[{"RequestType":112,"RequestMessage":[]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,115,144,77,93,252,109,224,211,162,85,162,193,47,53,153,226,88,100,195,178,24,54,17,28,196,103,252,238,78,4,205,22,120,140,236,88,28,30,238,147,249,234,188,36,59,251,58,110,43,251,39,177,72,40,71,85,29,190,16,124,153,43,118,103,97,95,211,224,16,243,178,61,243,81,178,17,12,114,206,78,31,125,23,149,125,97,2,10,95,55,147,28,147,136,110,1,165,62,233,111,120,167,191,132,39,28,149,203,4,146,117,184,0,142,97,205,129,161,147,185,88,7,59,230,145,90,223,246,63,216,134,186,196,55,177,136,164,207,0,65,194,238,88,111,136,86,114,2,218,72,96,234,18,55,90,50,177,66,95,43,86,120,209,153,185,235,117,241,210,183,228,27,41,167,234,111,90,67,96,227,7,22,6,27,39,104,1,70,6,80,123,246,82,252,201,112,184,205,243,207,40,200,84,43,226,146,231,18,104,242,86,120,159,242,240,76,38,155,242,11,201,171,246,51,191,20,165,58,58,92,231,178,29,88,57,155,38,159,185,242,68,81,160,159,170,174,125,20,147,244,42,155,89,164,253,226,37,142,83,32,41,128,104,131,115,165,109,15,143,47,73,95,25,55,185,13,17,159,231,170,113,121,93,224,204,126,129,162,171,159,183,72,43,23,102,246,187,172,161,145,164,91,212,247,90,110,188,36,227,207,14,102,172,57,154,103,133,129,29,87,4,171,191,43,136,142,66,26,97,102,102,107,95,154,253,124,6,175,179,83,189,116,218,89,154,231,242,96,19,17,34,132,11,116,15,173,139,4,67,244,207,42,128,53,26,240,5,199,21,131,162,66,241,7,195,69,97,159,84,44,171,102,196,169,201,149,162,10,26,180,158,105,38,145,164,172,87,152,131,186,7,44,199,152,211,106,116,71,170,124,113,221,242,154,103,235,99,144,77,45,106,160,199,149,187,60,102,126,188,136,55,161,188,87,7,122,30,227,240,72,252,47,3,211,184,184,10,147,156,188,12,149,238,253,231,60,216,189,167,29,132,225,89,87,28,190,184,239,37,90,28,210,226,74,214,198,144,211,190,23,72,82,33,17,222,119,94,167,26,160,106,22,24,50,120,50,50,104,157,221,112,153,41,178,61,180,217,44,75,91,26,203,97,56,49,205,145]}],"Latitude":34.008980302979424,"Longitude":-118.49782051532949,"Accuracy":30.345802172806952,"AuthInfo":null,"AuthTicket":{"Start":[3,244,139,92,213,235,60,119,243,22,190,120,2,59,42,78,27,184,24,130,123,61,84,190,87,233,42,186,42,242,108,208,27,242,112,6,86,216,134,142,146,223,190,222,201,79,215,95,137,10,98,254,46,79,220,240,229,115,45,88,26,72,5,72],"ExpireTimestampMs":1483704355650,"End":[155,90,201,79,249,186,12,181,161,77,200,121,104,84,25,38]},"MsSinceLastLocationfix":4659}
[18:36:14] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__3`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Inventory.<TransferPokemons>d__2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Inventory.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.TransferWeakPokemonTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\TransferWeakPokemonTask.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 93

**Comment by samuraitruong** [comment]
hard to debug this issue, please reduce Bulk size to avoid this happen. I will try to see it happy on my account

**Comment by jjskuld** [comment]
This is fixed now
