### ISSUE TITLE
Captcha resolving issue

### ISSUE THREAD

**Issue by Axeia** [Necrobot-Private/NecroBot#501]
My necrobot instance seems to be running into a problem with a captcha, I was away from my computer while it came up with a captcha and so missed the opportunity to resolve it.

Upon coming home I restarted the bot and it brings up this error:
```
[17:14:14] (INFO) Your IP is: XXX.XXX.XXX.XXX
[17:14:14] (UPDATE) Perfect! You already have the newest Version 1.0.0.53
[17:14:14] (INFO) Logging in using Ptc
[17:14:18] (INFO) Exception caught, writing LogBuffer.

Unhandled Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetPlayerData>d__27.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 353
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Error seems to be the same even after I changed the config to use 2captcha

### Your config.json:
```
  "CaptchaConfig": {
    "AllowManualCaptchaResolve": false,
    "ManualCaptchaTimeout": 120,
    "PlaySoundOnCaptcha": false,
    "DisplayOnTop": true,
    "Enable2Captcha": true,
    "EnableAntiCaptcha": false,
    "AntiCaptchaAPIKey": "201.33.206.229",
    "ProxyHost": "",
    "ProxyPort": 3128,
    "EnableCaptchaSolutions": false,
    "CaptchaSolutionAPIKey": "",
    "CaptchaSolutionsSecretKey": "",
    "AutoCaptchaTimeout": 120,
    "AutoCaptchaRetries": 3,
    "TwoCaptchaAPIKey": "000000000000000000000"
  },

```

The log doesn't mention anything not mentioned in the first block of text above. 

Windows Version: Windows 10 x64
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Cannot startup the bot.

_IP / 2captcha key censored_

**Comment by boscorelly** [comment]
same problem here

**Comment by DannyBoyCJ** [comment]
Just happened to me, exactly the same way it happened to Axeia above. Didn't solve the captcha in time, and now I'm unable to start the bot.

**Comment by Axeia** [comment]
Update:
The bot updated itself to the latest release and I have resolved the Captcha manually on an Android device. If I start Necrobot I still get the same error.

**Comment by samuraitruong** [comment]
did you have chrome install on your machine?

**Comment by Axeia** [comment]
Chrome is installed, Version 55.0.2883.87 m (64-bit) in its default location.

Perhaps worth noting is that I have SRWare Iron Browser installed as well (Chromium).

**Comment by boscorelly** [comment]
I have chrome too.

Did'nt have the problem before last release.

**Comment by DannyBoyCJ** [comment]
I have Chrome, I don't have Chromium. My system is win10/64, but I also tried on win7/64 and the result is the same.

**Comment by boscorelly** [comment]
reopen the issue !

**Comment by DannyBoyCJ** [comment]
Yes, why was it closed? It hasn't been solved! Or if you have a solution, please share!

**Comment by cosmickcan** [comment]
Hi Guys I have the same problem as above, all was well then got captched and did not respond in time, this time I thought the config file got corrupted, so reinstalled necrobot v2 again but still got the same problem please help

**Comment by samuraitruong** [comment]
It because you don't have chromedriver.exe in folder, you need get 0.56 build or download it manually, copy to bot folder then run it 1 time after that bot will able to trigger chrome, I going to enhance this to not using chrome

**Comment by boscorelly** [comment]
chromedriver was always present in the folder.
it was a buged release.

**Comment by DannyBoyCJ** [comment]
I also had chromedriver in my folder, and it triggered without a hitch before. My problem is gone now, but I used my phone to bypass the captcha so I don't know if it will resurface. I'm somewhat reluctant to try...

**Comment by DannyBoyCJ** [comment]
Nope, just happened again, with version .60 installed. So it's not solved.

**Comment by DannyBoyCJ** [comment]
Update: just bypassed it on desktop by manually starting chromedriver.exe (and leaving the window open), and only then executing necrobot2.exe. Google Chrome was also running, but I don't know if this is relevant.

**Comment by fedepasi** [comment]
I have the same problem and if i open chromedriver doesn't work... any idea?
