### ISSUE TITLE
Freezes when choosing gender

### ISSUE THREAD

**Issue by opera200** [Necrobot-Private/NecroBot#503]
Hi. I am absulutly new at boting and  I have problem. When I am trying to choose my gender and starter pokemon, bot freezes. In the log is nothing special I think.

 [21:10:42] () Configuration is up-to-date. Schema version: 6
[21:10:42] () Validating config.json...
[21:10:43] () Auth Configuration is up-to-date. Schema version: 6
[21:10:43] () Validating auth.json...
[21:10:43] () You bot will start after 15 second, You are running bot with  Legacy API (0.45) it will increase your risk to be banned and trigger captcha. Config captcha in config.json to auto resolve them
[21:10:47] (INFO) Your IP is: 89.249.94.233
[21:10:47] (UPDATE) Perfect! You already have the newest Version 1.0.0.53
[21:10:47] (INFO) Logging in using Ptc
[21:10:57] (INFO) Playing as k2126743
[21:10:58] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7851405053679 Lng: -73.9683287547583
[21:10:58] (ATTENTION) Without a Google Api, you will have 2500 free quota limit, if you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key
[21:10:58] (SERVICE) (Identity) [ 9abb6a51-b736-4069-9883-e7fc9c999b84 ] connection establisted

**Comment by msx752** [comment]
@opera200 `Set ActiveMSniper to False  in config file` msniper does not work under the windows 8 operating system

**Comment by opera200** [comment]
it wont help. And now i cant open the bot its says:

[17:14:14] (INFO) Your IP is: XXX.XXX.XXX.XXX
[17:14:14] (UPDATE) Perfect! You already have the newest Version 1.0.0.53
[17:14:14] (INFO) Logging in using Ptc
[17:14:18] (INFO) Exception caught, writing LogBuffer.

Unhandled Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetPlayerData>d__27.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Inventory.cs:line 353
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by samuraitruong** [comment]
fixed in #520
