### ISSUE TITLE
Error when autoupdate?

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#560]
Anyone has issue can you please post error message here

**Comment by DepecheMode2017** [comment]
yup .. the last 2 updates  gave a wall of red words but it still works. Couldn't update to .63 today so I downloaded and started from fresh ..

**Comment by timonibus** [comment]
The autoupdate fails but the bot continues to log in. The error is the following:

```
[14:29:16] (UPDATE) Downloading and apply Update...
[14:29:16] (INFO) https://github.com/Necrobot-Private/NecroBot/releases/download/v1.0.0.64/NecroBot2.Console.zip
[14:29:16] (INFO) Your IP is: xxx.xx.xxx.xxx
[14:29:21] (INFO) <PATH>\NecroBot2.Console.zip
[14:29:21] (UPDATE) Finished downloading newest Release...
[14:29:22] (UPDATE) Finished unpacking files...
[14:29:22] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[14:29:22] (ERROR) Error: System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at PoGo.NecroBot.Logic.State.VersionCheckState.MoveAllFiles(String sourceFolder, String destFolder) in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\VersionCheckState.cs:line 238
   at PoGo.NecroBot.Logic.State.VersionCheckState.<Execute>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\VersionCheckState.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 93
```

**Comment by jokki89** [comment]
I have the same problem as @timonibus  but as he says it still works after this error

**Comment by samuraitruong** [comment]
![image](https://cloud.githubusercontent.com/assets/1183138/22038533/a687bd40-dd4f-11e6-9bc1-97ed8fa2121c.png)

**Comment by sammy150681** [comment]
Cant update

**Comment by samuraitruong** [comment]
@sammy150681  you can download file and extract it to folder. I going fix auto update tonight

**Comment by sammy150681** [comment]
I dont want overwrite my personal file. What folder i have to replace?tnks

**Comment by sammy150681** [comment]
Errore from wesocker port 14251

**Comment by samuraitruong** [comment]
fixed https://github.com/Necrobot-Private/NecroBot/pull/572
