### ISSUE TITLE
Error loop Bad Request

### ISSUE THREAD

**Issue by crwys123** [Necrobot-Private/NecroBot#622]
Bot was running just fine for over an hour. Then I got an error saying to send it to dev ASAP so I figured I would share. Running Windows 10, 32-bit, Necrobot v1.0.0.69 Native GUI. Just doing the usual routine below 4kmh, catching pokemon and farming pokestops. Then got hit with this error, bot would try to log back in, would log in, then error again. It did it a few times in a row because I didnt notice at first. I re opened the console version and it seems to be fine now, haven't tried to WIN version yet. Also the hash server response has been really slow, anyone else experiencing this?

`[21:04:16] (ERROR) Bad Request - If you see this message please conpy error log & screenshot send back to dev asap.
[21:04:16] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":8835477455700492303,"Requests":[{"RequestType":101,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,48,55,49,50,56,54,57,48,48,54,53,53,51,56,17,220,129,225,2,23,113,67,64,25,28,242,209,169,198,66,83,192,33,175,233,173,95,16,113,67,64,41,0,0,128,85,197,66,83,192]}],"PlatformRequests":[{"Type":8,"RequestMessage":[]},{"Type":6,"RequestMessage":[10,133,4,201,181,129,189,174,34,153,103,41,213,235,23,48,232,93,70,97,236,154,249,177,170,190,227,37,235,176,26,251,224,26,2,114,125,134,95,97,16,208,134,18,241,4,173,182,151,207,73,140,11,119,130,54,107,157,18,206,183,44,226,168,67,114,180,130,61,1,70,231,97,152,55,37,150,201,59,7,59,204,139,169,164,63,247,79,253,128,144,132,179,18,79,39,209,22,192,97,189,151,62,151,239,126,68,11,241,253,181,178,25,83,217,215,131,54,53,7,240,187,136,219,233,144,136,97,178,148,181,153,109,82,145,224,149,205,230,255,23,7,189,179,4,108,165,221,40,31,29,95,211,48,55,1,92,31,39,46,59,8,100,176,160,55,216,97,240,48,151,183,89,35,6,116,213,59,212,121,218,53,205,61,210,92,237,65,176,76,156,235,67,25,220,98,5,82,201,29,211,14,150,229,81,133,82,180,80,209,214,63,216,185,172,87,204,5,243,133,7,58,20,33,110,101,249,252,181,92,218,136,29,35,188,130,133,111,66,246,132,203,188,159,84,139,2,139,173,92,80,119,68,240,250,246,163,29,35,238,105,30,95,93,132,35,206,104,29,225,220,216,137,13,225,250,144,26,193,174,81,162,2,253,231,24,53,234,100,20,254,17,149,90,193,177,166,91,91,233,69,208,245,229,218,35,200,215,4,64,198,125,184,211,124,209,203,25,103,9,9,61,67,40,254,127,132,131,220,154,155,73,66,225,6,63,72,92,175,114,77,130,152,25,157,193,76,200,163,108,150,148,35,149,57,49,178,109,72,236,180,120,129,121,142,89,184,78,151,144,253,134,96,122,19,16,154,26,137,155,126,111,174,244,252,54,65,7,110,9,199,53,188,41,214,130,48,197,122,60,210,194,249,232,147,59,233,142,65,67,139,49,186,239,71,252,10,1,241,125,36,42,55,200,244,47,155,84,113,110,39,5,96,90,194,210,88,148,45,114,190,53,254,56,177,144,103,198,37,78,25,36,206,48,172,228,177,2,3,218,163,158,238,210,205,82,150,231,235,154,17,101,216,186,193,196,134,130,166,117,78,46,108,243,203,44,206,170,62,27,92,93,148,118,225,208,121,227,17,230,201,144,216,251,76,255,26,141,14,173,229,223,107,183,22,164,249,143,247,241]}],"Latitude":38.883514747725457,"Longitude":-77.043375449204575,"Accuracy":42.059453419623644,"AuthInfo":null,"AuthTicket":{"Start":[224,139,243,225,52,179,11,56,83,228,156,64,193,41,231,9,127,189,248,149,228,151,62,61,118,12,168,97,86,187,128,167,248,165,169,215,48,103,96,49,165,23,19,154,48,132,68,129,76,104,24,159,114,114,60,163,102,115,29,142,40,111,170,157],"ExpireTimestampMs":1485149634933,"End":[63,25,228,14,53,105,169,221,214,121,45,70,124,65,14,72]},"MsSinceLastLocationfix":4111}
[21:04:16] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__3`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<SearchFort>d__2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<FarmPokestop>d__17.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 360
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<DoActionAtPokeStop>d__15.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 289
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 97
`

**Comment by samuraitruong** [comment]
can you send the log file?

**Comment by crwys123** [comment]
Yes I can. Just got to work though so it will be a while, sorry.

**Comment by crwys123** [comment]
Log file attached

[NecroBot2-2017-01-22-19-39-31.txt](https://github.com/Necrobot-Private/NecroBot/files/725416/NecroBot2-2017-01-22-19-39-31.txt)

**Comment by jjskuld** [comment]
I think this has been fixed after changes to inventory. Please reopen if you see the same exact error.
