### ISSUE TITLE
fix the null pointer check

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#642]
[23:43:59] (EVOLVED) Potential Evolutions: 0
[23:44:00] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[23:44:00] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<PrintPokemonInfo>d1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__4.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 468

**Comment by samuraitruong** [comment]
fixed
