### ISSUE TITLE
In-game Errors

### ISSUE THREAD

**Issue by DepecheMode2017** [Necrobot-Private/NecroBot#651]
I kept getting red wall of words .. Nantic scanning for botters? Hash server unstable? After the 2nd message I closed the bot ..

[14:27:45] (EVOLVED) Potential Evolutions: 0
[14:27:45] (INFO) Amount of Pokemon Seen: 75/151, Amount of Pokemon Caught: 74/151
[14:27:58] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[14:27:58] (ERROR) Error: System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v123_1/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 44
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(RequestEnvelope requestEnvelope) in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 263
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__25.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 330
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Map.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<GetNearbyPokemons>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 97
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v123_1/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 44<---

[14:27:58] (INFO) Logging in using XXXXXXXX
[14:28:29] (INFO) Playing as XXXXXXXXXX
[14:28:29] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7839143366066 Lng: -73.9704530896974
[14:28:29] (ATTENTION) Without a Google Api, you will have 2500 free quota limit, if you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key
[14:28:32] (EGG) Incubator status update: 4.68km left
[14:28:32] (INFO) Pokeballs: 0 | Greatballs: 95 | Ultraballs: 125 | Masterballs: 0
[14:28:32] (INFO) Potions: 2 | SuperPotions: 8 | HyperPotions: 10 | MaxPotions: 0
[14:28:32] (INFO) Revives: 10 | MaxRevives: 0
[14:28:32] (INFO) Berries: 50 | Incense: 8 | LuckyEggs: 5 | Lures: 5
[14:28:32] (INFO) Amount of Pokemon Seen: 75/151, Amount of Pokemon Caught: 74/151
[14:29:45] (INFO) (CATCH LIMIT) 114/998
[14:29:45] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 12 CP: (156/233) IV: 29.00% | Chance: 43.22% | 56.61m dist | with a GreatBall (94 left). | 120 EXP earned | Candies: 21 | lat: 40.784221 long: -73.969917 | Move1: TackleFast Move2: AerialAce | Rarity :VeryCommon
[14:30:15] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[14:30:15] (ERROR) Error: System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v123_1/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 44
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(RequestEnvelope requestEnvelope) in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 263
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__25.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 330
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__26.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:line 337
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__3`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<GetFort>d__1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 97
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.HasherException: Hash API server (http://pokehash.buddyauth.com/api/v123_1/hash) might down!
   at PokemonGo.RocketAPI.Hash.PokefamerHasher.<RequestHashesAsync>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Hash\PokefamerHasher.cs:line 44<---

[14:30:15] (INFO) Logging in using XXXXXXXXX

**Comment by samuraitruong** [comment]
hash server down
