### ISSUE TITLE
Error Level up pokemon?

### ISSUE THREAD

**Issue by wilsondgonzales** [Necrobot-Private/NecroBot#70]
```
[23:46:15] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[23:46:16] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<>c__DisplayClass23_0.<GetHighestPokemonOfTypeByIv>b__0(PokemonData x) in C:\projects\necrobot\PoGo.NecroBot.Logic\Inventory.cs:line 270
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestPokemonOfTypeByIv>d__23.MoveNext() in C:\projects\necrobot\PoGo.NecroBot.Logic\Inventory.cs:line 270
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.LevelUpPokemonTask.<UpgradeSinglePokemon>d__2.MoveNext() in C:\projects\necrobot\PoGo.NecroBot.Logic\Tasks\LevelUpPokemonTask.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__3.MoveNext() in C:\projects\necrobot\PoGo.NecroBot.Logic\Tasks\LevelUpPokemonTask.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.HumanRandomActionTask.<Execute>d__1.MoveNext() in C:\projects\necrobot\PoGo.NecroBot.Logic\Tasks\HumanRandomActionTask.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot\PoGo.NecroBot.Logic\State\FarmState.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57
```

Don't know what part of the config this would pertain to so i didn't post a long config file but im guessing it's the upgrade part so

```
"AutomaticallyLevelUpPokemon": true,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": false,
    "AmountOfTimesToUpgradeLoop": 50,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 100.0,
    "UpgradePokemonMinimumStatsOperator": "and",
```

**Comment by XurWuy** [comment]
Please paste the whole config file. Looks like you have missed the ";" or "," somewhere in the config....

**Comment by erickerich** [comment]
I got this error too. I don't think that come with missed the ";" or "," somewhere in the config. because bot will check config before it runs.

**Comment by Silph-Road** [comment]
^correct
