### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by jayhawkerkam** [Necrobot-Private/NecroBot#746]
Everything was running smoothly until the last update. Now I'm getting this:

[13:19:18] (INFO) You don't have pokemon to Dragonite to set as buddy
[13:19:20] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[13:19:20] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<GetNearbyPokemons>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 100

How do I fix?

**Comment by SLASHLogin** [comment]
In config try change your custom buddy.

**Comment by jayhawkerkam** [comment]
That fixed the buddy part, thank you.

However I'm still getting all those errors preventing it to run.

**Comment by jayhawkerkam** [comment]
Ah. Found the mistake. Had a digit off in my location. Problem resolved.
