### ISSUE TITLE
Captcha directly after login causes exception and login loop

### ISSUE THREAD

**Issue by 6Vampire6** [Necrobot-Private/NecroBot#765]
See topic - when the captcha is solved with the app/smartphone, login works again.
Remark: I have 2captcha configured to solve the captchas but for me it seems that the error occurs before the captcha is recognized by the bot.

Log:

[19:01:29] (INFO) Einloggen mit Ptc
[19:01:34] (INFO) Spiele als ...
[19:01:34] (INFO) [Recycle Configuration] Using recycle percents. Max Items: 350
[19:01:34] (INFO) [Recycle Configuration] Pokeballs (31%): 112
[19:01:34] (INFO) [Recycle Configuration] Potions   (32%): 112
[19:01:34] (INFO) [Recycle Configuration] Revives   (32%): 108
[19:01:34] (INFO) [Recycle Configuration] Berries   (0%): 0
[19:01:34] (ACHTUNG) Gehe sicher, dass Lat & Lng richtig sind. Schließe das Programm falls nicht! Lat: ... Lng: ...
[19:01:37] (INFO) ====== Hoechste WP ======
[19:01:37] (INFO) ====== Hoechste IV ======
[19:01:37] (ENTWICKELT) [Entwicklung] Moegliche Entwicklungen: 0
[19:01:37] (INFO) Keine Eier verfuegbar
[19:01:37] (EI) Ei-Brutmaschine Status Update: 1.20km verbleibend
[19:01:37] (INFO) Anzahl gesehener Pokemon: 148/151, Anzahl gefangener Pokemon: 147/151
[19:01:39] (FEHLER) Pokemon Servers might be offline / unstable. Trying again...
[19:01:39] (FEHLER) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<GetNearbyPokemons>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 100
[19:01:39] (INFO) Einloggen mit Ptc
... loop ...

**Comment by 6Vampire6** [comment]
Addition: Since this happened only once until now, I can't say for sure if the issue has to do with the captcha. But maybe the exception from the log can tell you something.

**Comment by bulubebek** [comment]
I have same issue, but I'm not opted with captcha when I login through my phone.

**Comment by hardknoxni69a** [comment]
i believe these issues have been resolved in latest issues please let us know if we need to reopen
