### ISSUE TITLE
Is this the right way to get Elevation api key?

### ISSUE THREAD

**Issue by ValorRed** [Necrobot-Private/NecroBot#77]
Version 0.9.8.7
I got the key from 
https://developers.google.com/maps/documentation/elevation/get-api-key
Put it under "GoogleAPIKey"

But getting under error when starting the bot. Then it failed to connect to Niantic server.
[21:37:15] Error: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Model.Google.GoogleWalk..ctor(GoogleResult googleResult) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:line 14
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__2.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__14.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63

**Comment by ajns73** [comment]
Make sure you enable that API under that key

**Comment by mjusuf** [comment]
try my solution
open https://console.developers.google.com/project//apiui/credential
open tab "Library" in left panel
see "Google Maps APIs" and select "More"
select "Google Maps Elevation API"
in top panel, select "ENABLE"
wait 5 - 10 seconds

if not working, open "Credentials" in left panel
select your project and make sure you only have one API key

**Comment by ntatoo** [comment]
"GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "Inside Here Your Google API",
    "Cache": true

**Comment by ValorRed** [comment]
Thanks for the info. In the Library, besides "Google Maps Elevation API", is there any other API I shall enable? I remember the first time when the Google Walk was introduced, there was a Wiki. It says there are 2 API need to enable, I lost track of it.
