### ISSUE TITLE
0.9.8.7 login error System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by vfuyong** [Necrobot-Private/NecroBot#78]
Config.json reconfigured manually, and this is the error upon login. Anyone has a similar issue?

[12:50:44] (INFO) System.ArgumentOutOfRangeException: Specified argument was out of the range of val
id values.
Parameter name: index
   at Google.Protobuf.Collections.RepeatedField`1.get_Item(Int32 index)
   at PokemonGo.RocketAPI.Rpc.Login.<FireRequestBlock>d__4.MoveNext() in C:\projects\necrobot2\Ferox
Rev\Rpc\Login.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at PokemonGo.RocketAPI.Rpc.Login.<FireRequestBlockTwo>d__5.MoveNext() in C:\projects\necrobot2\Fe
roxRev\Rpc\Login.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\projects\necrobot2\FeroxRev\Rpc\L
ogin.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.Ne
croBot.Logic\State\LoginState.cs:line 35

**Comment by erickerich** [comment]
same here. But it seems only  got this error once.

**Comment by vfuyong** [comment]
@erickerich Do you mean the bot will continue to work after seeing this error?

**Comment by erickerich** [comment]
yes, it will continue to work and won't appear again.

**Comment by vfuyong** [comment]
I just tried it again, this time I don't see the error but the bot hangs after showing pokemon catpured over pokedex...hmm....

**Comment by erickerich** [comment]
0.9.8.7 seems running slowly. The  delay  between every steps seems much longer than before.

**Comment by efifi** [comment]
the delay is because the settings are now 200,000 instead of 2,000 miliseconds - just reduce the delay timings

**Comment by vfuyong** [comment]
I did adjust the delay to be more reasonable, I believe it was not the cause..

**Comment by efifi** [comment]
there are 4 or 5 settings - all need to be changed

**Comment by ntatoo** [comment]
Please Delete Your Old Config File
And Try Again

Working Fine WIth me
