### ISSUE TITLE
Pokemon Servers might be offline / unstable. Trying again...

### ISSUE THREAD

**Issue by lito2506** [Necrobot-Private/NecroBot#80]
I am getting the error below.

`
[13:02:59] Pokemon Servers might be offline / unstable. Trying again...
[13:03:01] Error: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Model.Google.GoogleWalk..ctor(GoogleResult googleResult) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:line 14
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__2.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__14.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63`

**Comment by BoydTM** [comment]
Same... First run with "(INFO) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index"
and after that:
![necerror](https://cloud.githubusercontent.com/assets/21159620/18425522/7df2f506-78ba-11e6-87e3-ced7f625760f.jpg)

**Comment by BoydTM** [comment]
Repeated ... related with google API key

**Comment by LobsterX** [comment]
[13:49:03] Logging in using Google
[13:49:04] Playing as MarcoOngWP
[13:49:04] Make sure Lat & Lng are right. Exit Program if not! Lat: 1.28340094367874 Lng: 103.857872014029
[13:49:04] ====== DisplayHighestsCP ======
[13:49:04] # CP 2786/2800 | (96.17% perfect)	| Lvl 28	 NAME: Dragonite 	 MOVE1: DragonBreathFast     MOVE2: DragonPulse          Candy: 10
[13:49:04] # CP 2256/2301 | (85.13% perfect)	| Lvl 27	 NAME: Arcanine  	 MOVE1: FireFangFast         MOVE2: Bulldoze             Candy: 11
[13:49:04] # CP 2115/2153 | (86.88% perfect)	| Lvl 26	 NAME: Exeggutor 	 MOVE1: ZenHeadbuttFast      MOVE2: SolarBeam            Candy: 58
[13:49:04] # CP 1954/1959 | (98.25% perfect)	| Lvl 26	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: HydroPump            Candy: 343
[13:49:04] # CP 1926/1959 | (87.98% perfect)	| Lvl 26	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: HydroPump            Candy: 343
[13:49:04] # CP 1765/1823 | (76.44% perfect)	| Lvl 21	 NAME: Snorlax   	 MOVE1: LickFast             MOVE2: HyperBeam            Candy: 1
[13:49:04] # CP 1681/1697 | (93.73% perfect)	| Lvl 24	 NAME: Nidoking  	 MOVE1: FuryCutterFast       MOVE2: Megahorn             Candy: 91
[13:49:04] # CP 1652/1668 | (93.23% perfect)	| Lvl 24	 NAME: Nidoqueen 	 MOVE1: BiteFast             MOVE2: Earthquake           Candy: 72
[13:49:04] # CP 1599/1697 | (63.48% perfect)	| Lvl 28	 NAME: Pinsir    	 MOVE1: RockSmashFast        MOVE2: XScissor             Candy: 347
[13:49:04] # CP 1597/1621 | (90.81% perfect)	| Lvl 26	 NAME: Starmie   	 MOVE1: TackleFast           MOVE2: HydroPump            Candy: 309
[13:49:04] # CP 1477/1508 | (87.11% perfect)	| Lvl 24	 NAME: Rapidash  	 MOVE1: LowKickFast          MOVE2: HeatWave             Candy: 69
[13:49:04] # CP 1476/1510 | (84.45% perfect)	| Lvl 20	 NAME: Flareon   	 MOVE1: EmberFast            MOVE2: HeatWave             Candy: 137
[13:49:04] # CP 1456/1459 | (98.30% perfect)	| Lvl 19	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: DragonPulse          Candy: 343
[13:49:04] # CP 1439/1622 | (21.28% perfect)	| Lvl 22	 NAME: Venusaur  	 MOVE1: VineWhipFast         MOVE2: PetalBlizzard        Candy: 253
[13:49:04] # CP 1429/1445 | (92.25% perfect)	| Lvl 20	 NAME: Victreebel	 MOVE1: RazorLeafFast        MOVE2: SludgeBomb           Candy: 95
[13:49:04] # CP 1423/1452 | (86.19% perfect)	| Lvl 20	 NAME: Blastoise 	 MOVE1: WaterGunFast         MOVE2: HydroPump            Candy: 59
[13:49:04] # CP 1408/1568 | (31.22% perfect)	| Lvl 23	 NAME: Golduck   	 MOVE1: ConfusionFast        MOVE2: HydroPump            Candy: 1543
[13:49:04] # CP 1375/1400 | (85.51% perfect)	| Lvl 14	 NAME: Dragonite 	 MOVE1: SteelWingFast        MOVE2: DragonClaw           Candy: 10
[13:49:04] # CP 1341/1438 | (54.16% perfect)	| Lvl 21	 NAME: Clefable  	 MOVE1: ZenHeadbuttFast      MOVE2: Psychic              Candy: 76
[13:49:05] # CP 1310/1347 | (84.14% perfect)	| Lvl 27	 NAME: Fearow    	 MOVE1: SteelWingFast        MOVE2: Twister              Candy: 433
[13:49:05] # CP 1305/1332 | (87.13% perfect)	| Lvl 21	 NAME: Tentacruel	 MOVE1: AcidFast             MOVE2: Blizzard             Candy: 188
[13:49:05] # CP 1298/1309 | (94.57% perfect)	| Lvl 21	 NAME: Starmie   	 MOVE1: WaterGunFast         MOVE2: PowerGem             Candy: 309
[13:49:05] # CP 1296/1306 | (94.80% perfect)	| Lvl 17	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: Twister              Candy: 343
[13:49:05] # CP 1291/1309 | (91.48% perfect)	| Lvl 21	 NAME: Starmie   	 MOVE1: TackleFast           MOVE2: HydroPump            Candy: 309
[13:49:05] # CP 1281/1287 | (96.70% perfect)	| Lvl 16	 NAME: Vaporeon  	 MOVE1: WaterGunFast         MOVE2: WaterPulse           Candy: 137
[13:49:05] ====== DisplayHighestsPerfect ======
[13:49:05] # CP 1031/1034 | (98.51% perfect)	| Lvl 22	 NAME: Electrode 	 MOVE1: TackleFast           MOVE2: Thunderbolt          Candy: 291
[13:49:05] # CP 1456/1459 | (98.30% perfect)	| Lvl 19	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: DragonPulse          Candy: 343
[13:49:05] # CP 1954/1959 | (98.25% perfect)	| Lvl 26	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: HydroPump            Candy: 343
[13:49:05] # CP  522/ 524 | (97.01% perfect)	| Lvl 10	 NAME: Dodrio    	 MOVE1: SteelWingFast        MOVE2: AerialAce            Candy: 180
[13:49:05] # CP  221/ 222 | (96.84% perfect)	| Lvl 04	 NAME: Pinsir    	 MOVE1: RockSmashFast        MOVE2: XScissor             Candy: 347
[13:49:05] # CP 1281/1287 | (96.70% perfect)	| Lvl 16	 NAME: Vaporeon  	 MOVE1: WaterGunFast         MOVE2: WaterPulse           Candy: 137
[13:49:05] # CP  360/ 362 | (96.59% perfect)	| Lvl 05	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: HydroPump            Candy: 343
[13:49:05] # CP   37/  38 | (96.55% perfect)	| Lvl 01	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: HydroPump            Candy: 343
[13:49:05] # CP  733/ 738 | (96.52% perfect)	| Lvl 24	 NAME: Eevee     	 MOVE1: QuickAttackFast      MOVE2: Swift                Candy: 137
[13:49:05] # CP  561/ 564 | (96.45% perfect)	| Lvl 08	 NAME: Poliwrath 	 MOVE1: BubbleFast           MOVE2: IcePunch             Candy: 436
[13:49:05] # CP 1091/1097 | (96.45% perfect)	| Lvl 20	 NAME: Golbat    	 MOVE1: BiteFast             MOVE2: OminousWind          Candy: 455
[13:49:05] # CP  694/ 699 | (96.39% perfect)	| Lvl 20	 NAME: Pidgeotto 	 MOVE1: SteelWingFast        MOVE2: AirCutter            Candy: 2
[13:49:05] # CP  772/ 778 | (96.35% perfect)	| Lvl 19	 NAME: Graveler  	 MOVE1: MudSlapFast          MOVE2: Dig                  Candy: 116
[13:49:05] # CP 2786/2800 | (96.17% perfect)	| Lvl 28	 NAME: Dragonite 	 MOVE1: DragonBreathFast     MOVE2: DragonPulse          Candy: 10
[13:49:05] # CP  866/ 872 | (95.37% perfect)	| Lvl 14	 NAME: Starmie   	 MOVE1: TackleFast           MOVE2: PowerGem             Candy: 309
[13:49:05] # CP   25/  25 | (95.30% perfect)	| Lvl 01	 NAME: Kingler   	 MOVE1: MudShotFast          MOVE2: XScissor             Candy: 509
[13:49:05] # CP 1268/1278 | (95.27% perfect)	| Lvl 21	 NAME: Starmie   	 MOVE1: TackleFast           MOVE2: HydroPump            Candy: 309
[13:49:05] # CP  198/ 200 | (94.88% perfect)	| Lvl 03	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: DragonPulse          Candy: 343
[13:49:05] # CP 1296/1306 | (94.80% perfect)	| Lvl 17	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: Twister              Candy: 343
[13:49:05] # CP  877/ 885 | (94.64% perfect)	| Lvl 17	 NAME: Kingler   	 MOVE1: MetalClawFast        MOVE2: XScissor             Candy: 509
[13:49:05] # CP 1298/1309 | (94.57% perfect)	| Lvl 21	 NAME: Starmie   	 MOVE1: WaterGunFast         MOVE2: PowerGem             Candy: 309
[13:49:05] # CP  618/ 623 | (94.57% perfect)	| Lvl 10	 NAME: Starmie   	 MOVE1: WaterGunFast         MOVE2: Psychic              Candy: 309
[13:49:05] # CP  272/ 275 | (94.47% perfect)	| Lvl 10	 NAME: Goldeen   	 MOVE1: MudShotFast          MOVE2: AquaTail             Candy: 395
[13:49:05] # CP 1681/1697 | (93.73% perfect)	| Lvl 24	 NAME: Nidoking  	 MOVE1: FuryCutterFast       MOVE2: Megahorn             Candy: 91
[13:49:05] # CP  109/ 112 | (93.70% perfect)	| Lvl 15	 NAME: Magikarp  	 MOVE1: SplashFast           MOVE2: Struggle             Candy: 343
[13:49:05] Incubator status update: 2.13km left
[13:49:05] Potential Evolutions: 0
[13:49:07] Amount of Pokemon Seen: 129/151, Amount of Pokemon Caught: 129/151
[13:49:07] No usable PokeStops found in your area. Is your maximum distance too small?
[13:49:08] Traveling to gym : Marina Bay Sands Hotel | Lat: 1.282699 , Lng: 103.860697| (323.88m)
[13:49:08] Pokemon Servers might be offline / unstable. Trying again...
[13:49:09] Error: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Model.Google.GoogleWalk..ctor(GoogleResult googleResult) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:line 14
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__2.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__14.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 63

**Comment by vfuyong** [comment]
I had "System.ArgumentOutOfRangeException" too.

**Comment by BoydTM** [comment]
just make sure that you have API with direction and elevation enabled on your account

https://developers.google.com/maps/documentation/directions/get-api-key
https://developers.google.com/maps/documentation/elevation/start#get-a-key

**Comment by erickerich** [comment]
I don't think it related with Google api key. Turn off AutomaticallyLevelUpPokemon, it will no long appear.

**Comment by BoydTM** [comment]
In my case it was set to false since the beggining, regenerating keys helped ...

**Comment by ntatoo** [comment]
"GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": null,
    "Cache": true

If you want to use google route : "UseGoogleWalk": false, Set It To true
https://developers.google.com/maps/documentation/directions/get-api-key
https://developers.google.com/maps/documentation/elevation/start#get-a-key
