### ISSUE TITLE
Bug leads to crash

### ISSUE THREAD

**Issue by organicbetty** [Necrobot-Private/NecroBot#808]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Expected Behavior:

Runs normally

### Actual Behavior:

Crashes
### Your config.json:
```
unknown
```

### (OPTIONAL) Your Log:
```
[15:52:49] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[15:52:49] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":16531731,"Requests":[{"RequestType":103,"RequestMessage":[9,232,240,147,113,37,50,252,150,16,1,25,51,51,51,51,51,51,255,63,34,11,56,57,99,50,53,57,48,51,102,99,100,40,1,49,0,0,0,0,0,0,240,63,57,0,0,0,0,0,0,240,63]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,151,180,189,138,163,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,101,51,102,49,53,55,98,55,57,48,98,51,51,51,55,50,100,50,48,52,50,57,52,53,98,56,50,57,101,102,56,102,56,100,56,55,101,48,51,97]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,49,77,9,151,150,56,255,50,93,99,162,132,145,218,225,15,164,219,94,39,35,155,172,193,85,178,221,162,6,55,225,218,241,171,249,134,67,51,65,130,58,116,178,9,10,198,252,4,55,243,146,227,58,2,195,163,137,63,152,143,216,101,138,174,166,73,114,103,126,176,221,112,35,249,145,170,44,203,86,88,186,32,4,51,45,162,212,112,213,52,171,134,82,67,157,143,238,46,201,244,225,153,119,136,118,72,166,203,220,163,103,163,172,179,106,125,45,31,209,94,247,135,62,170,212,11,50,166,130,206,88,67,87,179,242,106,163,27,101,92,137,56,161,143,181,61,101,163,192,11,37,23,39,123,43,187,164,48,8,82,144,184,201,35,50,156,169,153,247,93,216,119,52,15,1,95,227,230,149,109,124,36,147,33,5,226,120,124,13,217,90,200,176,206,106,198,241,253,88,88,10,209,255,75,186,224,120,236,222,149,237,40,77,18,253,162,150,92,74,216,246,1,56,137,181,250,172,163,40,243,75,174,225,37,151,213,174,134,177,163,96,114,26,220,85,31,171,189,14,13,121,124,83,32,250,123,16,6,94,190,113,189,108,68,47,95,185,138,238,22,209,43,238,229,206,110,153,3,174,191,134,99,32,47,26,126,1,248,173,67,107,177,120,20,2,48,197,176,37,146,106,31,40,236,155,227,182,170,132,159,77,163,201,79,83,97,112,101,121,8,167,224,161,35,251,165,27,107,249,249,237,94,101,199,66,52,87,158,85,175,226,2,41,150,18,24,75,102,208,163,170,109,223,44,176,163,125,82,88,220,241,176,126,66,11,117,223,100,133,175,22,165,127,186,69,220,58,139,76,62,208,147,42,168,135,22,164,10,123,51,216,177,107,11,62,174,221,130,217,161,153,25,189,252,106,192,221,105,34,254,5,36,2,149,122,214,59,144,97,184,177,55,150,160,213,72,182,127,45,60,31,160,153,130,147,154,214,197,144,95,60,2,185,207,243,227,121,249,80,241,149,56,45,71,164,110,158,59,198,143,245,150,128,216,123,6,168,217,21,168,207,171,29,174,241,92,30,39,144,63,134,64,186,249,154,118,20,92,229,98,147,186,16,17,63,206,133,109,160,159,112,59,214,3,62,244,45,214,112,55,180,218,35,255,195,105,107]}],"Latitude":40.749720000008665,"Longitude":-73.976153999859534,"Accuracy":30.0,"AuthInfo":null,"AuthTicket":{"Start":[255,146,49,169,164,201,86,52,126,161,225,34,223,128,194,185,212,40,55,34,5,107,180,223,117,221,143,130,160,184,0,85,125,95,45,121,215,67,230,179,123,66,207,19,181,229,235,149,7,229,247,179,255,42,62,215,81,49,113,48,113,70,201,71,239,124,199,88,41,91,11,211,224,210,251,189,104,166,73,243],"ExpireTimestampMs":1486886561658,"End":[60,23,95,250,20,10,121,232,20,17,13,124,43,216,86,157]},"MsSinceLastLocationfix":15982}
[15:52:49] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Encounter.<CatchPokemon>d__3.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Encounter.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__4.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 100
```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by hardknoxni69a** [comment]
please check out our latest version and delete your accounts.db cache and lastpos it will load your default and should be good to go let me know if we need to reopen
