### ISSUE TITLE
Error with bot

### ISSUE THREAD

**Issue by acidified** [Necrobot-Private/NecroBot#840]
Apologies if I did this wrong. First error I've ever had to report.

[10:46:38] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[10:46:38] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":1457850879,"Requests":[{"RequestType":103,"RequestMessage":[9,92,120,180,29,68,129,112,52,16,1,25,82,184,30,133,235,81,200,63,34,11,56,56,49,54,52,100,54,99,52,97,57,49,0,0,0,0,0,0,240,63,57,0,0,0,0,0,0,240,63]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,190,199,183,234,163,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,101,51,102,49,53,55,98,55,57,48,98,51,51,51,55,50,100,50,48,52,50,57,52,53,98,56,50,57,101,102,56,102,56,100,56,55,101,48,51,97]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,61,77,181,159,122,113,4,172,20,69,29,93,169,83,6,122,173,121,52,239,5,118,18,39,146,99,129,100,4,16,0,166,45,9,182,181,163,242,247,187,170,93,161,226,20,144,143,253,204,71,78,218,22,140,207,85,117,10,239,193,163,65,118,0,135,189,46,133,127,137,174,29,36,117,13,60,201,149,101,151,41,150,11,196,209,35,247,93,221,160,199,175,19,211,236,94,204,182,86,114,166,166,146,190,183,155,87,81,68,100,121,236,84,35,33,15,135,44,193,209,107,212,159,212,164,38,120,33,18,215,235,222,92,89,166,135,59,112,50,225,85,163,218,0,93,117,22,249,157,59,111,176,4,168,138,147,241,93,248,118,168,126,56,42,86,191,14,146,20,18,73,36,244,53,238,207,54,69,63,152,38,180,60,213,168,97,199,41,36,31,17,52,81,231,47,20,10,84,137,246,115,112,136,4,210,127,39,111,244,63,173,154,57,40,196,229,103,107,91,182,129,140,243,184,106,247,230,230,58,219,108,182,218,180,232,241,54,99,98,207,176,21,88,138,157,217,72,68,180,186,166,26,107,135,200,86,72,45,249,199,171,190,112,171,236,77,242,88,203,22,212,236,222,200,250,165,7,90,120,17,90,129,110,211,240,40,35,83,213,128,42,68,248,116,246,49,77,244,221,166,234,222,57,95,19,164,6,202,67,147,162,126,37,26,235,11,106,127,179,111,127,155,79,247,60,44,108,177,202,96,17,71,172,210,51,62,122,23,213,74,88,224,113,140,227,148,156,101,18,87,131,180,146,215,66,74,64,203,136,52,40,170,45,51,73,185,27,35,215,100,33,82,141,145,136,93,129,32,68,213,6,179,159,62,251,21,220,44,158,85,6,34,234,164,129,243,222,206,237,19,117,214,42,69,96,230,70,186,181,9,29,26,121,151,19,39,183,149,85,27,55,49,216,158,153,114,52,103,105,52,237,76,42,142,122,82,153,90,158,248,154,146,185,176,139,107,208,186,250,176,16,214,173,17,17,213,3,156,1,84,49,228,163,238,206,210,127,231,152,6,143,30,127,146,98,128,235,245,85,225,100,199,194,249,126,204,73,90,48,106,114,17,148,242,118,69,92,20,212,135,89,184,19,34,254,7,52,106,228,141,137,182,9,122,100,141,145]}],"Latitude":41.801424555423822,"Longitude":-85.420427782538809,"Accuracy":50.0,"AuthInfo":null,"AuthTicket":{"Start":[131,163,76,78,122,101,170,74,237,154,69,155,55,131,221,125,106,243,125,124,236,242,61,244,146,202,153,160,224,221,19,60,243,120,247,29,103,103,113,212,246,24,248,162,71,249,51,116,134,196,220,70,133,135,154,175,163,3,191,203,41,200,86,134,13,30,19,32,192,80,121,231,240,134,131,89,197,243,141,238],"ExpireTimestampMs":1487088486626,"End":[229,252,155,208,94,167,151,130,155,168,197,32,23,99,75,119]},"MsSinceLastLocationfix":9084}
[10:46:38] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Encounter.<CatchPokemon>d__3.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Encounter.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__4.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 100

**Comment by hardknoxni69a** [comment]
perfect thank you

**Comment by hardknoxni69a** [comment]
i believe this has been resolved in latest version try to deelte your cache and accounts.db let me know if we need to reopen
