### ISSUE TITLE
Bad Request after new update

### ISSUE THREAD

**Issue by anoop95g** [Necrobot-Private/NecroBot#855]
Got the following error. I have attached my config file as well.
[conig.txt](https://github.com/Necrobot-Private/NecroBot/files/778057/conig.txt)

[23:59:37] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.

[23:59:37] (ERROR) BAD REQUEST
{"StatusCode":2,"RequestId":1458777931,"Requests":[{"RequestType":103,"RequestMessage":[9,8,248,22,35,159,123,70,38,16,2,25,184,30,133,235,81,184,206,63,34,11,52,56,55,54,48,52,99,57,55,55,53,49,0,0,0,0,0,0,240,63,57,0,0,0,0,0,0,240,63]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,225,241,165,152,164,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,101,51,102,49,53,55,98,55,57,48,98,51,51,51,55,50,100,50,48,52,50,57,52,53,98,56,50,57,101,102,56,102,56,100,56,55,101,48,51,97]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,67,9,66,28,129,147,40,163,30,5,159,163,181,255,111,112,60,104,30,86,85,210,152,159,61,36,185,109,150,41,74,233,65,82,255,134,246,28,62,120,11,106,219,140,181,158,94,216,8,5,160,232,175,241,89,97,106,112,126,55,209,186,129,42,194,211,136,168,90,248,251,105,156,186,3,254,6,4,149,158,58,86,119,34,99,16,150,55,59,225,43,99,33,228,31,14,35,25,244,113,8,185,117,187,64,230,30,158,28,58,6,98,93,194,161,61,212,136,78,77,30,161,113,155,228,141,4,0,20,144,144,168,8,221,101,234,5,222,116,142,112,7,191,58,124,36,105,139,232,37,154,13,52,176,105,191,30,227,12,195,142,239,186,182,82,250,115,146,211,43,223,193,119,70,246,115,189,148,92,120,102,118,19,250,76,76,151,122,227,87,227,183,149,50,77,205,207,74,50,143,114,81,203,104,135,247,227,183,115,128,13,159,76,227,199,147,96,121,220,177,114,11,133,158,221,76,91,62,31,157,70,174,242,74,145,239,52,75,100,249,252,41,167,77,99,201,190,151,8,100,83,195,208,221,140,205,21,218,3,216,223,231,67,53,92,71,37,150,221,76,137,251,41,73,25,255,193,201,143,220,94,116,42,191,193,195,149,44,19,29,140,160,26,178,38,225,227,5,66,7,19,117,203,159,34,3,10,198,120,217,193,188,136,84,11,154,120,108,177,71,85,79,24,25,233,85,201,166,215,67,123,128,176,38,253,210,200,247,253,68,4,206,77,21,253,89,130,177,190,159,49,114,192,158,51,159,37,128,93,220,41,75,169,89,113,156,161,134,240,82,244,55,139,190,194,113,105,87,177,38,80,109,200,50,219,85,230,21,180,47,250,215,34,104,251,47,38,148,6,103,208,138,241,235,225,218,212,130,192,44,161,84,115,19,47,186,155,17,203,116,157,238,228,136,195,119,192,75,83,209,84,248,225,198,167,46,58,106,131,30,17,93,115,22,146,208,222,96,185,69,31,74,138,248,191,98,172,157,234,123,132,5,67,219,26,174,229,136,102,220,39,219,102,39,119,181,210,239,232,108,131,153,99,46,214,10,132,120,124,142,68,254,227,223,19,241,54,223,36,71,17,83,178,72,165,12,160,166,172,162,124,131,135,74,210,201,235]}],"Latitude":51.509378215364841,"Longitude":-0.12002952138876691,"Accuracy":10.0,"AuthInfo":null,"AuthTicket":{"Start":[55,54,27,105,238,167,172,216,225,205,244,10,209,35,120,167,76,32,253,103,206,106,41,111,129,41,95,29,192,4,34,73,229,80,228,49,87,247,136,115,38,130,174,194,149,254,166,105,137,238,182,67,249,59,24,89,182,118,43,6,141,90,4,234],"ExpireTimestampMs":1487184631399,"End":[179,139,158,180,202,193,225,216,156,97,162,189,9,60,79,236]},"MsSinceLastLocationfix":16093}
[23:59:37] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Encounter.<CatchPokemon>d__3.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Encounter.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__4.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 100

**Comment by hardknoxni69a** [comment]
pretty sure this was resolved with latest update try deleting your accounts.db and lastpos to start at default with latest version should be good let us know if we need to reopen
