### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by jayhawkerkam** [Necrobot-Private/NecroBot#870]
[11:51:56] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[11:51:56] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":194847477,"Requests":[{"RequestType":103,"RequestMessage":[9,206,239,110,51,110,220,117,104,16,2,25,154,153,153,153,153,153,241,63,34,11,56,55,98,99,99,53,102,53,48,98,53,40,1,49,0,0,0,0,0,0,240,63,57,0,0,0,0,0,0,240,63]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,247,150,181,192,164,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,101,51,102,49,53,55,98,55,57,48,98,51,51,51,55,50,100,50,48,52,50,57,52,53,98,56,50,57,101,102,56,102,56,100,56,55,101,48,51,97]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,72,11,51,198,31,163,62,200,241,180,18,200,156,169,32,163,230,219,21,199,230,182,184,58,216,151,21,221,246,36,192,61,214,203,202,254,67,173,66,151,125,41,244,207,30,62,96,62,16,125,182,61,198,128,242,151,102,53,78,191,132,60,19,3,22,162,60,114,29,81,130,129,240,200,106,163,245,143,20,153,255,161,110,163,187,56,163,70,56,6,155,99,74,48,231,197,155,147,237,114,66,151,162,252,239,43,108,134,110,227,25,26,29,114,156,241,17,254,135,136,45,173,194,136,111,114,212,77,84,131,94,11,51,0,215,189,221,184,194,93,2,224,252,182,96,225,94,138,221,192,191,44,154,250,72,250,52,236,160,123,223,9,222,178,145,7,78,205,229,98,108,251,37,35,223,244,147,0,210,98,78,76,124,93,16,215,57,154,0,84,95,141,3,172,15,131,105,184,249,199,254,182,255,213,218,52,26,126,140,142,182,34,215,48,4,146,0,188,28,167,217,182,29,124,230,104,87,129,211,1,181,133,130,193,3,109,36,28,43,132,144,73,44,243,72,27,31,94,231,232,116,12,32,114,248,253,247,167,135,112,176,218,236,101,70,214,219,29,86,252,196,190,174,206,127,151,139,78,7,171,31,174,80,227,4,217,120,188,111,138,57,160,114,11,192,142,23,6,181,124,91,171,159,213,74,166,49,174,131,246,22,124,166,203,240,138,88,163,153,160,223,35,3,66,81,64,201,237,118,48,168,212,42,44,92,48,188,239,49,195,21,4,198,179,254,95,108,209,220,140,48,48,120,12,171,31,74,254,176,255,222,67,27,105,108,250,26,236,250,12,71,24,172,93,3,213,192,177,214,61,106,67,110,21,120,231,129,175,54,136,93,57,81,18,83,111,248,35,34,133,76,154,53,26,45,30,170,246,204,160,130,133,32,175,159,117,115,140,63,140,12,19,160,220,128,32,44,181,22,73,73,156,101,169,156,241,209,115,184,39,77,105,209,194,213,125,89,99,59,226,26,234,35,174,59,115,165,30,106,53,143,119,111,231,61,58,37,60,255,176,23,72,160,78,121,17,219,121,44,174,205,147,121,152,18,108,97,87,155,229,172,139,246,182,88,223,93,102,97,238,151,52,25,7,163,24,66,10,116,193,0,163,102,247,180,253,234]}],"Latitude":38.84145,"Longitude":-97.610428,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[243,177,121,243,178,29,175,218,72,154,167,8,61,222,218,202,227,9,153,248,171,142,161,209,146,238,9,214,33,32,251,25,147,183,8,145,45,237,43,165,16,249,72,36,167,227,159,223,150,166,198,187,140,202,72,209,138,41,60,202,123,52,19,193,44,25,225,175,190,62,191,225,132,227,248,13,183,45,166,246],"ExpireTimestampMs":1487269294992,"End":[158,118,171,44,192,202,161,35,152,61,85,28,177,42,25,9]},"MsSinceLastLocationfix":9976}
[11:51:56] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Encounter.<CatchPokemon>d__3.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Encounter.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__4.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<OnWalkingToPokeStopOrGym>d__12.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass10_0.<<WalkingToPokeStop>b__0>d.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.FlyStrategy.<Walk>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\FlyStrategy.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__14.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__10.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 100

**Comment by hardknoxni69a** [comment]
thanks for posting this should be fixed in latest issues try deleting your last pos to start at default location and delete cache and accounts,db and should be good to go let me know if i need to reopen for you
