### ISSUE TITLE
Bad Request - If you see this message please copy error log & screenshot send back to dev asap.

### ISSUE THREAD

**Issue by GrimmHubber** [Necrobot-Private/NecroBot#956]
] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[22:15:58] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":1458777931,"Requests":[{"RequestType":101,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,51,51,48,54,57,53,55,53,52,48,57,49,51,48,17,23,52,150,210,179,14,62,192,25,236,91,6,136,230,149,73,192,33,96,67,70,210,179,14,62,192,41,0,0,0,136,230,149,73,192]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,242,235,137,155,166,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,100,52,100,101,101,101,51,51,54,56,52,102,49,55,53,97,99,98,54,52,51,53,54,54,97,56,98,51,101,56,101,56,101,97,98,102,52,97,98,101]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,99,99,116,47,141,166,0,218,230,53,53,202,162,27,214,142,234,45,149,84,112,113,168,135,205,26,220,124,127,186,233,173,55,23,80,245,194,165,128,106,163,252,107,188,160,113,209,29,168,135,146,184,238,8,62,27,198,202,99,11,250,167,150,12,168,155,22,11,170,115,226,52,209,232,29,42,222,135,111,172,2,130,134,217,231,3,59,91,29,216,175,239,222,5,122,171,189,133,231,91,43,28,115,131,1,252,194,174,131,105,72,140,134,41,39,134,65,21,85,4,112,128,142,64,35,33,136,235,193,120,102,200,28,196,179,184,132,136,195,153,71,6,6,229,12,83,46,41,127,209,216,47,41,127,244,20,248,201,87,37,149,34,61,211,51,88,24,171,16,81,23,88,15,206,206,133,193,199,194,11,225,255,239,166,1,11,108,188,236,185,15,115,231,194,70,221,19,1,218,201,188,190,241,37,25,28,214,57,160,227,174,149,230,1,233,144,80,84,49,113,242,122,16,15,197,137,158,7,122,54,72,49,16,120,70,52,72,68,133,5,118,198,123,202,253,53,123,225,20,175,161,47,157,251,69,144,105,122,60,10,192,32,115,85,86,13,220,62,245,199,208,245,177,240,234,238,206,167,196,153,19,86,54,170,2,108,57,30,35,109,158,236,144,216,217,121,175,216,135,248,97,106,224,44,116,171,191,62,45,129,195,74,33,190,207,251,1,182,6,154,57,15,196,63,204,170,112,31,56,251,94,246,254,205,211,143,106,161,236,143,54,82,86,18,170,147,75,206,40,30,23,241,218,9,182,254,185,98,61,239,115,112,193,49,71,139,133,140,165,62,39,84,44,152,203,220,93,61,235,174,35,92,22,37,236,56,168,179,82,46,233,24,41,46,121,51,150,46,14,135,214,111,223,218,45,1,207,245,241,6,249,66,120,44,66,218,94,86,130,125,96,155,94,208,71,118,27,74,162,111,33,89,7,5,145,224,193,15,58,140,75,166,55,245,189,8,186,139,196,237,85,191,109,215,243,56,104,146,84,104,118,74,144,229,66,24,180,161,4,181,142,41,135,170,124,152,215,180,67,193,102,195,58,29,85,27,155,212,58,188,98,91,199,71,129,245,71,164,198,248,1,99,181,242,79,17,162,170,95,12,182,236,204,208,166,181,138]}],"Latitude":-30.057431375189562,"Longitude":-51.1710977583933,"Accuracy":65.0,"AuthInfo":null,"AuthTicket":{"Start":[82,173,76,90,184,77,93,32,51,115,255,183,34,187,33,10,135,240,24,39,65,163,166,3,189,17,196,71,242,75,171,165,252,125,251,245,22,167,53,253,201,232,106,134,117,199,156,85,147,141,249,162,162,66,162,247,148,94,48,16,224,66,67,72,124,193,50,45,157,27,144,14,54,159,144,115,243,195,43,181],"ExpireTimestampMs":1487726640986,"End":[138,207,60,144,113,88,187,145,152,118,49,39,104,242,88,128]},"MsSinceLastLocationfix":17205}
[22:15:58] (ERROR)    em PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() na c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:linha 129
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() na c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:linha 174
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() na c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:linha 46
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() na c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:linha 130
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() na c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:linha 119
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.Fort.<SearchFort>d__2.MoveNext() na c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:linha 77
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<FarmPokestop>d__17.MoveNext() na c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:linha 392
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<DoActionAtPokeStop>d__15.MoveNext() na c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:linha 307
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() na c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:linha 68
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() na c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:linha 60
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() na c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:linha 54
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() na c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:linha 101

**Comment by elmoo568** [comment]
I believe I'm seeing the same bug, I got it in one of my accounts and the bot keeps logging back in but as soon as it does, I get the error message.  It looks very similar to the above except my error is in English.  After I stopped the bot, I restarted it a few minutes later and it ran fine.  Second time it's happened today:

[23:24:26] (ERROR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[23:24:26] (ERROR) BAD REQUEST 
{"StatusCode":2,"RequestId":2007237711,"Requests":[{"RequestType":101,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,52,48,48,50,51,55,51,52,57,48,50,50,55,52,17,29,27,156,46,63,97,68,64,25,116,250,255,135,200,126,82,192,33,89,51,2,46,63,97,68,64,41,0,0,0,136,200,126,82,192]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,251,197,137,234,168,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,99,49,102,50,54,49,49,98,102,57,49,100,48,49,57,102,48,97,54,54,48,101,54,102,51,56,98,48,99,51,97,50,54,97,51,54,98,97,53,48]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,141,66,218,109,54,49,172,239,128,77,218,97,11,52,122,25,192,247,184,26,121,203,212,131,237,219,110,38,38,231,0,145,117,3,29,12,255,0,189,56,193,183,21,33,78,87,169,58,65,86,129,51,197,7,5,86,230,220,143,0,231,205,165,45,90,244,247,211,224,7,144,87,85,228,192,123,26,24,58,81,83,194,221,76,35,211,241,227,67,203,178,174,29,214,37,7,101,39,105,141,236,1,25,163,151,145,207,98,203,211,78,136,123,45,208,222,38,173,179,234,198,41,149,57,203,190,200,182,46,115,245,76,132,224,161,131,104,175,34,235,81,153,152,85,118,168,133,113,13,179,178,188,166,171,40,223,226,75,90,132,242,231,53,255,100,138,214,144,166,200,78,11,115,138,112,230,223,204,123,128,194,173,50,111,155,221,157,137,41,98,37,162,88,167,4,70,129,209,99,10,202,183,135,36,48,84,169,118,72,75,172,87,106,168,197,44,112,147,70,82,217,68,215,188,101,147,204,237,48,44,255,244,140,238,132,1,149,134,111,140,77,202,81,242,158,7,67,9,247,239,39,82,165,120,116,216,27,117,36,115,208,67,172,211,36,205,44,235,157,204,20,209,148,180,7,176,57,112,34,147,78,191,83,204,252,24,14,196,148,95,148,204,170,117,180,42,69,61,199,151,62,111,51,147,226,245,95,174,38,37,189,24,92,220,228,41,135,118,75,207,241,128,220,95,242,50,92,71,17,233,192,122,223,11,111,177,241,5,104,253,70,142,33,50,73,210,25,153,136,65,111,53,33,156,85,173,27,211,59,239,125,40,233,36,133,164,85,242,108,219,59,78,205,63,189,113,1,66,70,103,8,245,61,221,104,93,191,35,208,207,195,133,214,30,194,96,143,197,33,150,174,129,203,217,11,117,19,102,92,231,200,11,141,179,81,146,227,240,186,187,248,33,128,233,17,218,212,241,233,243,58,69,125,147,39,65,41,28,141,93,18,146,23,172,77,187,81,51,72,205,179,122,195,217,194,9,116,73,210,177,65,250,207,191,181,36,120,13,155,183,91,69,84,4,189,79,16,164,43,19,228,222,127,246,128,25,93,88,119,140,144,164,149,138,19,75,159,250,163,36,39,189,91,47,181,3,173,212,34,131,121,118,175,220,152,253,51]}],"Latitude":40.759740663741674,"Longitude":-73.980989456156578,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[159,137,195,178,240,171,20,183,79,40,249,73,6,25,70,86,194,232,219,151,44,110,46,210,89,164,83,182,161,249,84,255,93,177,215,158,147,46,26,227,141,110,253,145,163,194,88,217,2,20,69,42,125,179,74,190,131,23,16,106,108,249,182,135],"ExpireTimestampMs":1488428683742,"End":[203,172,25,72,199,21,156,106,213,255,38,89,53,61,45,2]},"MsSinceLastLocationfix":3528}
[23:24:26] (ERROR)    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Fort.<SearchFort>d__2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<FarmPokestop>d__17.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<DoActionAtPokeStop>d__15.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 307
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 101

**Comment by hardknoxni69a** [comment]
attaching to #1156
