### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by Cooljewover9000** [Necrobot-Private/NecroBot#981]
This keeps popping up when I start up Necrobot. I have tried using Different API's with multiple accounts and this keeps happening every time. I am using a google api for the api's i am using.

[19:55:23] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__4`2.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\LoginState.cs:line 50

**Comment by Doctor06** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/980

**Comment by Cooljewover9000** [comment]
You mean Niantic?
